### ISSUE TITLE
Tkinter method Tk() failed with error message

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#201]
**[Original report](https://bitbucket.org/ronaldoussoren/pyobjc/issue/201) by T M (Bitbucket: [teammember100](https://bitbucket.org/teammember100), ).**

----------------------------------------

When I called the Tkinter method Tk(), I see this error message: 

 -[NSApplication _setup:]: unrecognized selector sent to instance

A window is displayed but none of the widgets are in it. When I resize the window it changes color from white to black. 

Here is what the code I use look like:

mywindow = Tk()
label = Label(mywindow, text="Hi")
label.pack()

**Comment by MacDaddy1660B** [comment]
> **Original comment by Ronald Oussoren (Bitbucket: [ronaldoussoren](https://bitbucket.org/ronaldoussoren), GitHub: [ronaldoussoren](https://github.com/ronaldoussoren)).**
> 
> I've asked the pythonmac-sig mailinglist if someone knows a way to integrate Tkinter into a Cocoa program.
> 
> One thing to try is to create the Tk() object before starting the main Cocoa runloop.

@ronaldoussoren thank you for the tip! This helped me identify a bug with an application I'm developing.
