### ISSUE TITLE
subclass in iOS run successfully in simulator but failed in iPhone

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#208]
**[Original report](https://bitbucket.org/ronaldoussoren/pyobjc/issue/208) by iosdeveloper (Bitbucket: [__bridge_retained](https://bitbucket.org/__bridge_retained), ).**

----------------------------------------

Hi Ronald,

Thanks for your great job.
I'm trying to use pyobjc in a iOS project, following code can run in simulator:

```
import objc
from Foundation import CGRectMake
UIApplication = ObjCClass("UIApplication")
UIColor = objc.lookUpClass('UIColor')
UIView = objc.lookUpClass("UIView")

rootVC = UIApplication.sharedApplication().keyWindow().rootViewController()
rc = CGRectMake(30,70,50,60)

class MyView(UIView):
    def initWithFrame_(self, frame):
        self = UIView.alloc().initWithFrame_(frame)
        self._.backgroundColor = UIColor.redColor()
        return self

aView = MyView.alloc().initWithFrame_(rc);
rootVC._.view.addSubview_(aView)
```

But failed in iPhone, crashe in function initWithFrame, any idea?

![exception.JPG](https://bitbucket.org/repo/5ej88/images/3820287237-exception.JPG)

**Comment by guysoft** [comment]
Hey, was wondering if @ronaldoussoren got it to work somehow on iOS, or if there is another solution out there, perhaps using Pyobjus?

**Comment by ronaldoussoren** [comment]
Again: PyObjC is a project for macOS not iOS. If that changes it will be mentioned in the announcement for the release where it changes (and for completeness, that's not something I'm working on).

**Comment by guysoft** [comment]
Ah. My bad, I didn't realize that the issue was migrated from bitbucket and though that your handle was the original poster.  I was wondering if the original poster some some iOS equivalent.
