### ISSUE TITLE
Missing framework wrapper: AGL

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#224]
**[Original report](https://bitbucket.org/ronaldoussoren/pyobjc/issue/224) by Ronald Oussoren (Bitbucket: [ronaldoussoren](https://bitbucket.org/ronaldoussoren), GitHub: [ronaldoussoren](https://github.com/ronaldoussoren)).**

----------------------------------------

Add framework wrapper for the AGL framework (or document that it won't be wrapped)

**Comment by HiImJulien** [comment]
My guess, you can drop that, due to Apple's decision to deprecate OpenGL anyways. It is quite possible, that the next iteration of macOS (coming with the new ARM-based macBooks) won't come with OpenGL support.

**Comment by ronaldoussoren** [comment]
As already mentioned in the framework overview the AGL framework will not be wrapped.
