### ISSUE TITLE
metadata on custom objects

### ISSUE THREAD

**Issue by schriftgestalt** [ronaldoussoren/pyobjc#298]
(running python code inside an app written in ObjectivC)

I have an object with a property defined like this:
```
typedef NSObject<GSContainerProtocol> GSContainer;

@property (weak) GSContainer *parent;
```
If I access it from python, I get this:
```
print(anObject.parent())

>>> ObjCPointerWarning: PyObjCPointer created: at 0x6110000c8180 of type ^{NSObject=#}16@0:8
>>> <PyObjCPointer object at 0x119851490>
```

If I use the type definition directly, it works fine:
 ```
@property (weak) NSObject<GSContainerProtocol> *parent;
```
I notices that the signatures of `parent` are different:
With the typedef I get`b'^{NSObject=#}16@0:8'`
with the direct type I get this: `b'@16@0:8'`

Why is that different and is there a way to fix this on my end?

**Comment by ronaldoussoren** [comment]
Sigh. That's a compiler bug. 

The following probably works (but I haven't tested this yet):

```
import objc
objc.registerCFSignature("NSObject", b"^{NSObject=#}", 0, objc.lookUpClass("NSObject"))
```

This misuses the bridge metadata system to register the type encoding you're seeing as a CoreFoundation type that's toll-free bridged to NSObject. 

I'll work on a proper fix.

**Comment by ronaldoussoren** [comment]
This bug appears to be fixed in the current Xcode 11.4 beta. 

I expect to commit a workaround for this in PyObjC later tonight.

**Comment by schriftgestalt** [comment]
If it is a bug in clang, that is already fixed, you can ignore this. Don’t add future cruft. 
I can avoid I for now.

**Comment by ronaldoussoren** [comment]
The cruft is a couple of lines of code, nothing too bad. 

The fix will be in the next release of PyObjC, which will be released after the release of Xcode 11.4.

**Comment by schriftgestalt** [comment]
Thank you for your prompt replies.

**Comment by schriftgestalt** [comment]
The code sample does indeed helped with this. But is has to be like this:
```
import objc
objc.registerCFSignature("NSObject", b"^{NSObject=#}", 0, "NSObject")
```
