### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pyobjc-framework-LaunchServices==6.2.1 

### ISSUE THREAD

**Issue by aboretto** [ronaldoussoren/pyobjc#307]
aboretto@destructo-lap-top ~ % pip install pyobjc-framework-LaunchServices==6.2.1 --user
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Collecting pyobjc-framework-LaunchServices==6.2.1
  ERROR: Could not find a version that satisfies the requirement pyobjc-framework-LaunchServices==6.2.1 (from versions: 2.2b2, 2.2, 2.3, 2.4, 2.5.1, 3.0.1, 3.0.3, 3.0.4, 3.1, 3.1.1, 3.2, 3.2.1b1, 3.2.1, 4.0b1, 4.0, 4.0.1, 4.1, 4.2, 4.2.1, 4.2.2, 5.0a1, 5.0b1, 5.0, 5.1, 5.1.1, 5.1.2, 5.2, 5.3)
ERROR: No matching distribution found for pyobjc-framework-LaunchServices==6.2.1
aboretto@destructo-lap-top ~ %

**Comment by ronaldoussoren** [comment]
You appear to be using Python 2.7.  PyObjC 5.3 is the last version of PyObjC that supports Python2.7, the current version requires Python 3.6 or later.
