### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sabuu** [ronaldoussoren/pyobjc#312]
I am facing this error ..

Traceback (most recent call last):
  File "install.py", line 224, in <module>
    main()
  File "install.py", line 217, in main
    for project in ["pyobjc-core"] + sorted_framework_wrappers():
  File "install.py", line 130, in sorted_framework_wrappers
    cur_platform = get_sdk_level() or get_os_level()
  File "install.py", line 102, in get_os_level
    with open("/System/Library/CoreServices/SystemVersion.plist", "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'

**Comment by kainjow** [comment]
Are you installing on a Mac?

**Comment by ronaldoussoren** [comment]
A related question: why do you use the install.py script and not "pip install pyobjc"?

**Comment by ronaldoussoren** [comment]
I'm assuming you're not installing on macOS.
