### ISSUE TITLE
Error generate while installing on pyobjc in windows 10

### ISSUE THREAD

**Issue by Vikash-Sinha** [ronaldoussoren/pyobjc#313]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\vikas\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\vikas\\AppData\\Local\\Temp\\pip-install-rloms6uz\\pyobjc-framework-QTKit\\setup.py'"'"'; __file__='"'"'C:\\Users\\vikas\\AppData\\Local\\Temp\\pip-install-rloms6uz\\pyobjc-framework-QTKit\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\vikas\AppData\Local\Temp\pip-install-rloms6uz\pyobjc-framework-QTKit\pip-egg-info'
         cwd: C:\Users\vikas\AppData\Local\Temp\pip-install-rloms6uz\pyobjc-framework-QTKit\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\vikas\AppData\Local\Temp\pip-install-rloms6uz\pyobjc-framework-QTKit\setup.py", line 33, in <module>
        for fn in os.listdir("Modules")
      File "C:\Users\vikas\AppData\Local\Temp\pip-install-rloms6uz\pyobjc-framework-QTKit\pyobjc_setup.py", line 412, in Extension
        os_level = get_os_level()
      File "C:\Users\vikas\AppData\Local\Temp\pip-install-rloms6uz\pyobjc-framework-QTKit\pyobjc_setup.py", line 200, in get_os_level
        with open("/System/Library/CoreServices/SystemVersion.plist", "rb") as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ronaldoussoren** [comment]
PyObjC cannot be installed on Windows, it is a library specific for macOS.
