### ISSUE TITLE
Drop embedded copy of libffi

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#314]
In macOS 10.9 and later (at least, haven't checked earlier versions) there's a copy of libffi that's shipped with the system with headers in the SDK. This means we no longer need our own copy of libffi.

I therefore want to drop the local copy of libffi in PyObjC 7.

**Comment by kainjow** [comment]
+1 to this. Any timeframe for this change?

**Comment by ronaldoussoren** [comment]
The embedded copy is gone in the PyObjC 7 branch, which will be released slightly before the release of macOS 11.

**Comment by ronaldoussoren** [comment]
Done in the pyobjc-7-branch, which now builds and runs on macOS 10.9 as well as 11.0 (both arm64 and intel).

I still have to test that weak linking works by smoke testing a pyobjc-core wheel build on 11.0 on a 10.9 VM, but that should work just fine...
