### ISSUE TITLE
implicitly declaring library function 'bzero' in _AppKit_nsbitmap.m

### ISSUE THREAD

**Issue by kainjow** [ronaldoussoren/pyobjc#319]
I'm testing out the `pyobjc-7-branch` branch:

```sh
pip install --verbose --no-deps -e git+https://github.com/ronaldoussoren/pyobjc.git@pyobjc-7-branch"#egg=pyobjc-framework-Cocoa&subdirectory=pyobjc-framework-Cocoa"
```

but I get:

```
In file included from Modules/_AppKit.m:14:
Modules/_AppKit_nsbitmap.m:104:9: error: implicitly declaring library function 'bzero' with type 'void (void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        bzero(dataPlanes, sizeof(dataPlanes));
        ^
Modules/_AppKit_nsbitmap.m:104:9: note: include the header <strings.h> or explicitly provide a declaration for 'bzero'
```

It looks like this is the only use of `bzero` in pyobjc, but I see other uses of `memset`. Should this be changed to memset instead?

**Comment by ronaldoussoren** [comment]
Switching to memset should be fine, I usually use memset because that's what I've always used.

What I do no yet understand is why you get this error, I'd expect this to fail always or never...

What platform are you on?
- Python version, and how was it installed?
- macOS version
- Xcode version

**Comment by stbdang** [comment]
https://github.com/ronaldoussoren/pyobjc/pull/341
