### ISSUE TITLE
Adding more nssound methods

### ISSUE THREAD

**Issue by acemasterjb** [ronaldoussoren/pyobjc#326]
Hey so I'm making a music player right now that I'm hoping will be cross platform and I'd like to use NSSound for OSX support, can I assume that the [list of commands starting here](https://github.com/ronaldoussoren/pyobjc/blob/efecb479c3cf32ec1d36abfb9b7d7c8cfd4ede6d/pyobjc-framework-Cocoa/Lib/AppKit/_metadata.py#L17163) defines what methods are compatible once NSSound is initialised with an audio file?

```
from AppKit import NSSound

# example of using NSSound
load_audio = NSSound.alloc().initWithContentsOfURL_byReference_(url, True)

load_audio.play()
```

can I also use commands like

```
load_audio.currentTime()
```

like it's described [here](https://developer.apple.com/documentation/appkit/nssound/1477320-currenttime) on the appkit docs?

**Comment by ronaldoussoren** [comment]
All methods in the AppKit documentation for NSSound are supported through PyObjC.
