### ISSUE TITLE
Cutting a new release?

### ISSUE THREAD

**Issue by linuxfood** [ronaldoussoren/pyobjc#327]
Heya @ronaldoussoren thanks for merging my PR awhile back! I hate to nag, but is there a chance a new release could be cut? I'm currently using a custom build of `pyobjc` for my application, and I'd like to be able to simply list the wheel from pypi in my `requirements.txt`.

If you're not interested in cutting a new release, do you have a sense of when you were thinking of cutting a new one?

**Comment by ronaldoussoren** [comment]
There will be no further releases of PyObjC 6.x.   

I just released PyObjC 7.1 (from the pyobjc-7-branch) and will be merging that branch into master laster this week.
