### ISSUE TITLE
Plesae release a new version (e.g. 6.2.3)

### ISSUE THREAD

**Issue by tasn** [ronaldoussoren/pyobjc#329]
First of all, thank you for this project!

My code using this library unfortunately doesn't work with 6.2.2 due to the issue fixed in 34d59f31e37a318b2374f019246bf10bdbb28acb. It would be great if you could make a new release with this commit included...

I hope this is the right place for this report, and thanks again!

**Comment by linuxfood** [comment]
Also: #327

**Comment by tasn** [comment]
@ronaldoussoren ping

**Comment by ronaldoussoren** [comment]
There will be no more releases in the PyObjC 6.x branch. I just released PyObjC 7.1 which should be better than the 6.x release train in all ways.

The only thing left to do w.r.t. 6.x is to tag the current head of the master branch and than merge the 7.x development branch into master.
