### ISSUE TITLE
Question: How to disable/skip a test?

### ISSUE THREAD

**Issue by SuperSandro2000** [ronaldoussoren/pyobjc#330]
I am packaging pyobjc for Nix and some tests are failing due to how Nix works. I would like to easily disable them but I couldn't find a flag or some argument to disable them. Is this possible and if yes how? Thanks!

**Comment by ronaldoussoren** [comment]
Tests are run using the stdlib unittest framework and can be marked for skipping or as known failures in the usual way (by adding a decorator the tests). 

What tests are failing?

**Comment by SuperSandro2000** [comment]
> by adding a decorator the tests

I was more on the search for a cli flag to easily skip tests on the fly.

> What tests are failing?

Multiple for various reasons wich are probably not related to the code but how nix handles stuff. I am not asking to fix them but for a simple way to skip them.

**Comment by ronaldoussoren** [comment]
Such a flag does not exist.

**Comment by SuperSandro2000** [comment]
pytest offers such flags but your tests are not compatible with that. Maybe something to support in the future.
