### ISSUE TITLE
Overriding makeViewWithIdentifier_owner_ in NSTableView

### ISSUE THREAD

**Issue by mischievous** [ronaldoussoren/pyobjc#332]
I am trying to override the makeViewWithIdentifier_owner_ in an NSTableView subclass.  It does not appear to be getting called.  

When I change the subclass to a delegate it works as expected.  

Is there an easy way to test if this in something I am doing incorrectly?  Is there an example of this working, that I can look at?

Thanks,
Alexandra

**Comment by mischievous** [comment]
Here is my customTableView 

class tableView  ( Cocoa.NSTableView ):

    #
    def init         (self):
        self = objc.super(alachemytableView, self).init()
        return self

    #
    def registerNib_forIdentifier_ (self, nib, identifier):
        print (identifier, nib)
        objc.super(alachemytableView, self).registerNib_forIdentifier_(nib, identifier)
        pass

    #
    def makeViewWithIdentifier_owner_ (self, identifier, owner):
        print (identifier, owner)
        return objc.super(alachemytableView, self).makeViewWithIdentifier_owner_(identifier, None)
        pass

**Comment by mischievous** [comment]
@ronaldoussoren 

I have created a actual obj-c project with custom NSTableView and NSNib along with category extensions for NSTableView and NSNib.  My dumb sample project works great with no issues.  

I have taken the same files and built a bundle out of the custom class and categories.  Loaded the bundle I think correctly (https://github.com/ronaldoussoren/pyobjc/blob/3bd289a7fa1749f459301ac599c63864b6a00947/docs/metadata/compiled.rst) but it still does not work.  

I have tried to find the metadata compiler mentioned above and can't find it.  I have tried to create manual metadata for the two classes but did not help.  

Am I missing something obvious?

**Comment by mischievous** [comment]
The code below works for the creating a category and replacing the "description" method.  But does nothing for the "makeViewWithIdentifier:owner:" method.  

The objective-c code works like its suppose to.

Alexandra

class NSTableView  ( objc.Category(NSTableView) ):
    __extensions__= {
                        'description'                   : Cocoa.NSTableView.instanceMethodForSelector_('description'                  ),
                         'makeViewWithIdentifier_owner_' : Cocoa.NSTableView.instanceMethodForSelector_('makeViewWithIdentifier:owner:'),
                    }

    def newDescription(self):
        return u'[was: %s]' % NSTableView.__extensions__['description'] (self)

    #
    objc.namedSelector(b"makeViewWithIdentifier:owner:")
    def newmakeViewWithIdentifier_owner_ (self, identifier, owner):
        print ('makeViewWithIdentifier_owner_', self, identifier, owner)
        return None

    #
    objc.classAddMethod (NSTableView, b"description", newDescription)
    objc.classAddMethod (NSTableView, b"makeViewWithIdentifier:owner:", newmakeViewWithIdentifier_owner_)

**Comment by ronaldoussoren** [comment]
One thing that's wrong here is the call to objc.classAddMethod, 

```
class NSTableView  ( objc.Category(NSTableView) ):
    ...

    def description(self):
        return u'[was: %s]' % NSTableView.__extensions__['description'] (self)

 
    def makeViewWithIdentifier_owner_ (self, identifier, owner):
        print ('makeViewWithIdentifier_owner_', self, identifier, owner)
        return None
```

This should do the trick.  One possible gotcha: this is just a more convenient way to add methods to an existing class, it is not possible to add new data attributes to instances (at least not for ObjC classes, for Python subclasses with an ``__dict__`` this is not a problem).

**Comment by ronaldoussoren** [comment]
The code in my previous message works for me.  I've also added some text to the documentation to hopefully make it clearer how the class should be used.
