### ISSUE TITLE
NSMutableArray.pop(n) raises error (in some situations...)

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#334]
The test suite for pyobjc-core fails due to anNSMutableArray.pop(1) raises an error. Running that particular test on its own does not raise an error.

It looks like a category on NSMutableArray adds a pop method on the ObjC side, hiding the convenience method added by PyObjC.

**Comment by schriftgestalt** [comment]
I just run into the same problem when running inside my app (objectiveC app loading the python framework)

**Comment by ronaldoussoren** [comment]
The problem here is that some category introduces an undocumented pop method in a subclasss of NSMutableArray, which is then bridged to Python as an argumentless ```pop()``` method. That method replaces the list-compatible implementation ```pop``` that I've added to the NSMutableArray proxy. 

I currently don't have an sane way to deal with this, other than trying to manually enumerate all subclasses of NSMutableArray and adding my implementation of pop to the proxy of those classses.  That would be pretty fragile and is not something I want to do.   

I hope to be able to fix this cleanly once I implement #306. That will move a lot of the interesting logic of build class proxies from Objective-C to Python, which should make it easier to add tweaks to that code.
