### ISSUE TITLE
Need pyobjc-framework-Cocoa>=7.0a1

### ISSUE THREAD

**Issue by yujie-tao** [ronaldoussoren/pyobjc#335]
Hi 

I am trying to get the latest version under `pyobjc-7-branch`. However, during installation, I received error saying I need `pyobjc-framework-Cocoa>=7.0a1`. Where I can download that version? I don't see it in the public release

`Installed /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyobjc_framework_Contacts-7.0a1-py3.7-macosx-10.9-x86_64.egg
Processing dependencies for pyobjc-framework-Contacts==7.0a1
Searching for pyobjc-framework-Cocoa>=7.0a1
Reading https://pypi.org/simple/pyobjc-framework-Cocoa/
No local packages or working download links found for pyobjc-framework-Cocoa>=7.0a1
error: Could not find suitable distribution for Requirement.parse('pyobjc-framework-Cocoa>=7.0a1')
Installing 'pyobjc-framework-Contacts' failed (status 1)`

**Comment by rongilson** [comment]
```
cd pyobjc-framework-Cocoa
python3 pyobjc-framework-Cocoa/setup.py install
```
once complete
```
cd pyobjc
python3 install.py
```

**Comment by ronaldoussoren** [comment]
Running "python3 develop.py" or "python3 install.py" from the root of the checkout should work. I mostly use the former when developing.

Note that PyObjC 7.0.1 is on PyPI and includes wheels.
