### ISSUE TITLE
Installation Error on MacOS Catalina 10.15.7 Python 3.6.4

### ISSUE THREAD

**Issue by emadul-credosense** [ronaldoussoren/pyobjc#343]
Collecting pyobjc-framework-Cocoa
  Downloading pyobjc-framework-Cocoa-7.0.1.tar.gz (3.4 MB)
     |████████████████████████████████| 3.4 MB 216 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/hackintosh2/PycharmProjects/soil-respiration/venv_mac/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-l8xztg5v/pyobjc-framework-cocoa_fc69776a3c2b488ca8ce25063747b645/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-l8xztg5v/pyobjc-framework-cocoa_fc69776a3c2b488ca8ce25063747b645/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-g2qwg4uz
         cwd: /private/tmp/pip-install-l8xztg5v/pyobjc-framework-cocoa_fc69776a3c2b488ca8ce25063747b645/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-l8xztg5v/pyobjc-framework-cocoa_fc69776a3c2b488ca8ce25063747b645/setup.py", line 26, in <module>
        extra_link_args=["-framework", "CoreFoundation"],
      File "/private/tmp/pip-install-l8xztg5v/pyobjc-framework-cocoa_fc69776a3c2b488ca8ce25063747b645/pyobjc_setup.py", line 434, in Extension
        % (tuple(map(int, os.path.basename(data)[6:-4].split("."))))
    ValueError: invalid literal for int() with base 10: ''
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ronaldoussoren** [comment]
What's the output of ``xcrun -sdk macosx --show-sdk-path`` on your system?   How did you install the compiler, did you install Xcode or the Command Line Tools for Xcode? And which version?

**Comment by ronaldoussoren** [comment]
#333 is the same issue on Big Sur.

**Comment by erikng** [comment]
In my testing of building pyobjc on Big Sur it will continue to fail if you only have the Xcode command line tools. If you have both command lines tools and Xcode installed you must force your CLI tools to use Xcode and not the command line tools.

I have yet to have a single successful install when compiling against the tooling.

I'm not sure if it's an Apple bug or something in the compile scripts but you may want to add a note about this.

Thanks,
Erik Gomez
________________________________

**Comment by ronaldoussoren** [comment]
I added some, mostly untested, code to pyobjc_setup.py to deal with this issue.  I don't know if this actually fixes the problem, I don't have machines with the Command Line Tools installed.

**Comment by emadul-credosense** [comment]
> What's the output of `xcrun -sdk macosx --show-sdk-path` on your system? How did you install the compiler, did you install Xcode or the Command Line Tools for Xcode? And which version?

output: 
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
I am using pycharm IDE version 2020.2.4

**Comment by emadul-credosense** [comment]
> I added some, mostly untested, code to pyobjc_setup.py to deal with this issue. I don't know if this actually fixes the problem, I don't have machines with the Command Line Tools installed.

I have tried to install it again but getting same kind of error

**Comment by ronaldoussoren** [comment]
I'm currently cloning a test VM to create one with the Command Line Tools installed.  I just committed some changes that allow me to build on macOS 10.10, but more changes are needed for recent versions of macOS.

BTW. A workaround is to install Python 3.8 or 3.9 instead of 3.6, there are binary wheels for those versions on PyPI. Python 3.6 is in security fix only mode and will never support macOS 11 (the same is true for 3.7).

**Comment by ronaldoussoren** [comment]
The issue is fixed in PyObjC 7.1 (fresh on PyPI)

**Comment by emadul-credosense** [comment]
Issue solved after upgrading my python version to 3.9. Thank you so much
