### ISSUE TITLE
Bug in test_cfmessageport?

### ISSUE THREAD

**Issue by gineer01** [ronaldoussoren/pyobjc#344]
In the test test_cfmessageport.py [1] , the callout returns "hello world":
```
        def callout(port, messageid, data, info):
            info.append((port, messageid, data))
            return b"hello world"
```

If I understand correctly, that means the request to the port will return "hello world" as data (see CFMessagePortCallBack doc [2]). However, the test validates that the returned data is `None`. Is this a bug? Why should `data` be `None` instead of `"hello world"`?

```
        err, data = CoreFoundation.CFMessagePortSendRequest(
            port, 99, None, 1.0, 1.0, None, None
        )
        self.assertEqual(err, 0)
        self.assertEqual(data, None)
``` 

[1] https://github.com/ronaldoussoren/pyobjc/blob/master/pyobjc-framework-Cocoa/PyObjCTest/test_cfmessageport.py#L88
[2] https://developer.apple.com/documentation/corefoundation/cfmessageportcallback?language=objc

**Comment by ronaldoussoren** [comment]
You appear to be right.  This is an API I don't use myself so I'm not 100% sure and will have to try to reproduce this in ObjC code to be certain.

**Comment by ronaldoussoren** [comment]
The test case was to simple and didn't invoke the callback function for CFMessagePortCreateLocal. After playing around with some Objective-C code I've updated the test and it now does the right thing. 

Luckily this only required changes to the test code, the actual binding worked fine.

Thanks for the report!
