### ISSUE TITLE
problems installing on older system (macOS 10.7)

### ISSUE THREAD

**Issue by ugokanain** [ronaldoussoren/pyobjc#346]
I have an old mac that can only run 10.7.5. It has a current version of python 3.9 and an almost current pip 20.3.3

However, I'm running into issues. On 5.3 you changed xcodebuild to xcrun. My version doesn't work as you expect it. Where I get **xcrun: error: unrecognized option: --show-sdk-path**

```
xcrun
Usage: xcrun [options] <utility> ... arguments ...

Find and execute the named command line utility from
the installed Xcode.

Options:
  -h, --help           show this help message and exit
  -v, --verbose        show verbose logging output
  --sdk <sdk name>     find the tool for the given SDK name
  --toolchain <name>   find the tool for the given toolchain
  -l, --log            show commands to be executed (with --run)
  -f, --find           only find and print the utility path
  -r, --run            find and execute the utility (this is the default behavior)
  -n, --no-cache       do not use the lookup cache
  -k, --kill-cache     remove any existing cache file (and perhaps recreate)
```

Did try to install 5.2 (sudo -H pip install -Iv pyobjc==5.2), but seems that my python version has deprecated some calls
` pl = plistlib.readPlist('/System/Library/CoreServices/SystemVersion.plist')
    AttributeError: module 'plistlib' has no attribute 'readPlist'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Any suggestion besides getting a newer system?

**Comment by ronaldoussoren** [comment]
That's annoying. I'm willing to review PRs that restore compatibility with 10.7 but no longer have a machine that's running that version of the OS.
