### ISSUE TITLE
pyobjc-framework-MetalPerformanceShaders cannot be compiled on Mojave due to unavailable protocol declarations

### ISSUE THREAD

**Issue by amyspark** [ronaldoussoren/pyobjc#348]
Hi again!

Like in #311, I find myself again unable to use pyobjc. This time it's MetalPerformanceShaders, which uses the following unavailable protocols on Mojave:

- MPSHeapProvider
- MPSNNGramMatrixCallback
- MPSNNLossCallback

There may be others, but this is where pip bailed out.

[80.pip.txt](https://github.com/ronaldoussoren/pyobjc/files/5999752/80.pip.txt)

**Comment by ronaldoussoren** [comment]
I'll fix this in the next release.

A question:  why do you use "pip install --no-binary"?  The binary wheels for PyObjC work should work fine on macOS 10.14, and will work on macOS 11 as well.  The Pyobjc-core won't work properly on macOS 11 when compiled on 10.14.

**Comment by amyspark** [comment]
@ronaldoussoren that question would be best directed at the maintainers of Homebrew. AFAIK, if a formula is Python-based, it always installed all its dependencies from source.

**Comment by ronaldoussoren** [comment]
Yeah, that's a homebrew thing. Understandably from their end, but a bit annoying when I've created binary wheels to avoid problems like this ;-)

**Comment by ronaldoussoren** [comment]
I've fixed this particular issue, but I'm not 100% sure that this is enough to build PyObjC using Xcode 10 (or the corresponding command-line tools).

The error should also go away when using the latest compiler version on Mojava (Xcode 11.1), that includes and SDK that does include these definitions.

**Comment by amyspark** [comment]
I can confirm pyobjc builds successfully now with Xcode 11.3.1!

(I downloaded the ZIP file from Github and tested it with `python install.py`.)
