### ISSUE TITLE
Quartz pyobjc library rejected by Apple

### ISSUE THREAD

**Issue by adigeo** [ronaldoussoren/pyobjc#371]
Hello,

Aftere pushing an update to Mac App Store, the app was sudenly rejected with the following reason:

```
From Apple

Guideline 2.5.1 - Performance

Your app links against the following non-public framework(s):

Quartz/CoreGraphics/_callbacks.cpython-39-darwin.so/_CGDataProviderCreateDirectAccess
Quartz/CoreGraphics/_callbacks.cpython-39-darwin.so/_CGDataProviderCreate
Quartz/CoreGraphics/_callbacks.cpython-39-darwin.so/_CGDataProviderCreateDirectAccess
Quartz/CoreGraphics/_callbacks.cpython-39-darwin.so/_CGDataProviderCreateSequential
Quartz/CoreGraphics/_callbacks.cpython-39-darwin.so/_CGDataProviderCreateWithData
```

**Comment by ronaldoussoren** [comment]
Ah, the joys of the App Store.   These are indeed no longer public APIs. PyObjC still links with them for compatibility with older OSes.  That said, it looks like these APIs were removed in macOS 10.8 and I support macOS 10.9 and later. I'll remove these bindings in PyObjC 8 (in October).

For now you'll have to remove the bindings manually by patching the corresponding source file and rebuilding the wheel.

And if you don't use any of the manual bindings in that file (see below) you can also remove the extension entirely and patch Quartz/CoreGraphics/__init__.py. 


Manual bindings in ``_callbacks``:

```
CGDataConsumerCreate
CGDataProviderCreate
CGDataProviderCreateDirectAccess
CGDataProviderCreateSequential
CGDataProviderCreateWithData
CGFunctionCreate
CGDisplayRegisterReconfigurationCallback
CGDisplayRemoveReconfigurationCallback
CGScreenRegisterMoveCallback
CGScreenUnregisterMoveCallback
CGRegisterScreenRefreshCallback
CGUnregisterScreenRefreshCallback
CGEventTapCreate
CGEventTapCreateForPSN
CGPatternCreate
CGPSConverterCreate
```

**Comment by ronaldoussoren** [comment]
BTW.  ``CGDataProviderCreateSequential`` and ``CGDataProviderCreateWithData`` are still public APIs, I've checked in the beta SDK for macOS 12.  The warnings for those might be due to a midding link flag in PyObjC's build process.

**Comment by adigeo** [comment]
Thank you Ronald!

I removed the bindings and submitted again.

**Comment by ronaldoussoren** [comment]
Out of interest: What's the app? And what do you use the build the app bundle?

**Comment by adigeo** [comment]
https://github.com/AGProjects/blink-cocoa

I use Xcode archive -> Then using the Organizer I upload to the store.

**Comment by adigeo** [comment]
The app was approved after the removal of _callbacks*

Hartelijk dank!

**Comment by adigeo** [comment]
Small gift sent using a Paypal pidgeon!
