### ISSUE TITLE
Compilation falis due an unused argument for v7.3 on Big Sur

### ISSUE THREAD

**Issue by yaitskov** [ronaldoussoren/pyobjc#375]
Hi,

I am trying to build pyobjc-framework-Cocoa with nix and I get compilation error:

```
 pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/b8f5b65cff8b3ca5a3e9e7d57dc873c92d536571.tar.gz") {}
}:
let
  my-coca = pkgs.python3Packages.buildPythonPackage rec {
    name = "pyobjc";
    version = "v7.3";

    src = pkgs.fetchFromGitHub {
      owner = "ronaldoussoren";
      repo = "${name}";
      rev = "${version}";
      sha256 = "0vspb77f436cjp4ykpyzijr8g4glzg6rbr2sks7dcwv9lgbaxi33";
    } + "/pyobjc-framework-Cocoa";

    propagatedBuildInputs = with pkgs.python3Packages; [ setuptools pytest ];
  };

in pkgs.mkShell { buildInputs = [ my-trash  ] ; }
```

> 
> 
> uilding 'CoreFoundation._inlines' extension
> creating build/temp.macosx-10.6-x86_64-3.8
> creating build/temp.macosx-10.6-x86_64-3.8/Modules
> clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/4i\
> 5w9iv836cg6hgr02g6phds6br8nas0-python3-3.8.9/include/python3.8 -c Modules/_CoreFoundation_inlines.m -o b\
> uild/temp.macosx-10.6-x86_64-3.8/Modules/_CoreFoundation_inlines.o -Wno-deprecated-declarations -isysroo\
> t /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -DPyObjC_BUILD_RELEASE=1103 -Werror
> clang-7: error: argument unused during compilation: '-fno-strict-overflow' [-Werror,-Wunused-command-lin\
> e-argument]
> error: command 'clang' failed with exit status 1
>

**Comment by ronaldoussoren** [comment]
``-fno-strict-overflow`` is not used in the PyObjC sources and is likely added by your build system.

As a workaround you could add a patch that removes the logic for adding ``-Werror`` from ``pyobjc_setup.py`` (and different logic to remove the same flag from ``pyobjc-core/setup.py``)
