### ISSUE TITLE
Add bindings for IOBluetooth framework

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#381]
See #380, the framework has Python users.

**Comment by dlech** [comment]
Hi @ronaldoussoren,

How hard would this be for someone not named Ronald to implement?

**Comment by ronaldoussoren** [comment]
Fairly hard, for two reasons:

1. The tooling I use is currently tuned for my laptop and workflow (and AFAIK it is not in sync with the public version of that tooling)
2. IOBluetooth contains a number of APIs that require manual bindings (such as ``IOBluetoothPackData``). 

That said, the headers look less daunting than when I first looked at them, other than the sheer size.  There might be a dependency on IOKit.framework, but on first glance it should be possible create bindings without creating full IOKit bindings first.

**Comment by ronaldoussoren** [comment]
Sigh, I also need to tweak the tooling, there's at least one struct containing a union that confuses the metadata scanning tool, seemingly due to getting bogus data from clang.

**Comment by ronaldoussoren** [comment]
The trunk now contains bindings for IOBluetooth and IOBluetoothUI. 

@dlech: If you want to test these bindings you can easily install them on top of the current release of PyObjC:
- Check out the repository
- Change the VERSION in pyobjc-framework-UIBluetooth and "python setup.py install"
- Change the VERSION in pyobjc-framework-UIBluetoothUI and "python setup.py install"

You can also perform a full install using the "install.py" or "develop.py" scripts, but that takes a while.

The bindings are as complete as I can make them at this time, in particular the bindings for IOBluetooth are incomplete due to a number of APIs that require manual bindings because they cannot be described by the metadata system (most importantly due to using a struct that contains a C union, but also a varargs function with a format string).

If you do end up testing this: please let me know if one of the missing APIs is necessary to actually use these APIs. I'm hoping they are not because most if not all of them are deprecated for a long time.

**Comment by dlech** [comment]
So far, so good, thanks! I've just been working with RFCOMM so far but haven't run into anything missing.
