### ISSUE TITLE
Add bindings for xpc/xpc.h

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#382]
See title, likely name for the package: pyobjc-framework-libxpc (similar to how the dispatch.h bindings are named)

**Comment by glyph** [comment]
If this were done, would it be possible to write XPC clients and servers in Python?

**Comment by ronaldoussoren** [comment]
That's the intention.  This would be more inconvenient than using the Objective-C APIs for this, but those require writing protocols in ObjC to use the API (annoyingly enough the runtime APIs for creating protocols do not create protocols that are accepted by the XPC classes).

**Comment by ronaldoussoren** [comment]
The interface is fairly low-level, resulting in fairly verbose code because conversion from basic Python types to the corresponding xpc type has to be done manually (e.g. ``xpc.xpc_bool_create(True)``). 

It is possible to improve on this by adding some convenience APIs (such add adding ``__getitem__`` to XPC_TYPE_ARRAY and XPC_TYPE_DICTIONARY), but this first version is a direct mapping from the C API.

These bindings have seen only very light testing, basically on the unit tests that mostly check that APIs are present with the correct metadata for them. That said, I don't expect many problems: the only function that needed special support is xpc_dictionary_create and the python binding for that was simple enough. 

BTW. It should be possible to test the new bindings with the current release of PyObjC by changing the version in setup.py before trying to install it. That saves a lot of time compiling the rest of PyObjC.
