### ISSUE TITLE
request for python3.8 universal2 wheels

### ISSUE THREAD

**Issue by AndrewHoos** [ronaldoussoren/pyobjc#387]
It would be nice to have python3.8 universal2 wheels now that python.org offers universal2 python3.8 installers. If this not a large burden to add it would be nice. If this is a huge hassle no worries :)

Python3.8 universal2 download source:
https://www.python.org/downloads/release/python-3810/

**Comment by ronaldoussoren** [comment]
I'll look into this for PyObjC 8 later this year.  Adding those wheels won't be hard, I already have the scripting set up to build and test multiple variants of the python.org installer.   I do hope that this installer supports older version of macOS as well, my plan for Python 3.9 and 3 .10 is to only supply universal2 wheels, as those will work with single architecture builds as well.

TBH I didn't know that anyone had bothered to back port the Universal 2 patches to 3.8.

**Comment by ronaldoussoren** [comment]
BTW. I would advise moving to 3.9 unless you have dependencies that don't support it yet.

One teaser for PyObjC 8: it will feature a number of performance improvements, but for the most part only when using Python 3.9 or later.   Expected release is around the time macOS 12 is released.

**Comment by AndrewHoos** [comment]
Totally in favor of python3.9 I was just trying to support a user that needed python3.8 because reasons... on surprised by getting the building wheel dialog and delay when installing `pyobjc-core`. Will do my part to nudge people to 3.9 and 3.10 when it comes out. Thanks for everything you do

**Comment by ronaldoussoren** [comment]
I've installed 3.8-universal2 on my test/develop/build VMs, which will then be used for the next release.

I'll upload 3.8-universal2 wheels for the current release as well, I have a VM building the wheels and will upload those later today.

**Comment by ronaldoussoren** [comment]
I've uploaded universal2 wheels for python 3.8 to PyPI (for the about 10 subproject that need them, some subproject either don't need binary wheels or use the limited ABI).
