### ISSUE TITLE
[Question] Using Apple Pay API with an Electron-like program

### ISSUE THREAD

**Issue by Dsibe** [ronaldoussoren/pyobjc#402]
Hello!

I would like to a deploy a program (more on which later) to the Apple Store, and I have a couple of questions regarding Apple Pay API usage.
My product will be a paid program, and I have some problems with the Apple Pay API due to technical reasons.

My program is an "Electron-like" application, it consists of two parts, backend, and UI.
The "Backend" runs directly in the user's computer, it's written in Python and Flask.
The "UI" is actually a browser that opens a webpage from the "Backend", and interacts with it using AJAX.

The issue here is that I don't understand how in-app payments can be implemented.
As far as I understand, the only option to deploy a paid application and the Apple Store is to use Apple Pay API, which is only available from Swift or Objective-C.
I don't understand how can I use Apple Pay API, how I can check for a valid payment, etc.
Is it possible to use PyObjc to somehow use Apple Pay API?

Thank you very much.

P.S.
If you need any other technical information, I will provide it.

**Comment by ronaldoussoren** [comment]
This should be possible using PyObjC, although you might run into incompatibilities between your application structure and the available APIs.

AFAIK in-app purchases can be implemented using the StoreKit framework and that framework is available through PyObjC (pyobjc-framework-StoreKit).

I cannot help you w.r.t. how to use these APIs, I haven't used them myself.

**Comment by Dsibe** [comment]
Thank you for a very quick answer, I will try to read Apple's docs. I will add to this thread if I achieve some result using StoreKit API.
