### ISSUE TITLE
Bug with NSSavePanel

### ISSUE THREAD

**Issue by benwiggy** [ronaldoussoren/pyobjc#403]
The following code causes a 'non-fatal exception':

from AppKit import NSSavePanel
panel = NSSavePanel.savePanel()

Chatter on the internet suggests it might be a bug introduced in OS Catalina.

**Comment by ronaldoussoren** [comment]
Can you provide a bit more information? 

If this is a warning printed by ``-[NSSavePanel savePanel]``: I cannot fix bugs in system libraries, only those in the Python bindings.

**Comment by ronaldoussoren** [comment]
There's too little information here to determine what's wrong. I'm closing this issue for now and will reopen when you add information that can be used to reproduce the issue.
