### ISSUE TITLE
Segfault with 8.2 on macOS <= 10.14

### ISSUE THREAD

**Issue by Safihre** [ronaldoussoren/pyobjc#430]
We use PyObjC in our application (SABnzbd) for notifications, tray-menu and keep-awake actions.
Our release-tester @Cpuroast noticed our latest release crashes on macOS <= 10.14 while the previous release candidates worked just fine.
I noticed that the only difference was that PyObjC was automatically updated to 8.2. 
When we revert to 8.1, it works again.

@Cpuroast has also tested running SABnzbd from sources (the release is build using PyInstaller), but it also results in a segfault with 8.2, but not with 8.1 on macOS <= 10.14.

```
 ./SABnzbd 
Segmentation fault: 11

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [419]
```
Using Python 3.10.2 directly:
```
python3 ./SABnzbd.py
Segmentation fault: 11
```

Tested macOS versions:
macOS 10.10 Crash
macOS 10.11 Crash
macOS 10.12 Crash
macOS 10.13 Crash
macOS 10.14 Crash
macOS 10.15 Pass
macOS 11 Pass
macOS 12 Pass

Ref: https://github.com/sabnzbd/sabnzbd/issues/2046

**Comment by ronaldoussoren** [comment]
How easy is it to reproduce this issue?  Can I just run SABnzbd on a 10.14 or earlier system and easily see the crash, or do have I to perform specific action to trigger the crash?

I have some virtual machines running older versions of macOS, I'll also check if just running PyObjC's testsuite on an older macOS release triggers the issue.

One more question: Did you install PyObjC from PyPI or through some other repository (like anaconda)?  If the latter, please run: ``otool -vL $(python3 -c 'import objc; print(objc._objc.__file__)')``. This will print the shared libraries used by the core of PyObjC, and I'm in particular interested to know if this contains a link to a libffi dylib (it won't in the regular build).

**Comment by Safihre** [comment]
It should be really straight forward, just using stock Python 3 from python.org:
```
# Get python from python.org
git clone https://github.com/sabnzbd/sabnzbd
cd sabnzbd
pip3 install -r requirements.txt 
python3 SABnzbd.py
```
The requirements don't list specific PyObjC version, so it will pull in 8.2.

**Comment by ronaldoussoren** [comment]
There will probably be a 8.3 release this weekend, I think I've found the problem but need to perform some more testing.

The crash is embarrassingly easy to reproduce with only PyObjC:

1. ``pip install pyobjc``
2. ``python -c "import Foundation"``

Some cleanup work broke the way I detect which libffi system APIs I can use, and resulted in trying to dereference a NULL pointer while trying to call a function that's not actually available on older macOS versions.

**Comment by maxbelanger** [comment]
I can confirm this also broke tests for the Dropbox application on macOS 10.10 - 10.14.

**Comment by ronaldoussoren** [comment]
Sorry about the delay.

I've just uploaded PyObjC 8.3 to PyPI and that should fix this issue.
