### ISSUE TITLE
Question about Virtualization.Framework

### ISSUE THREAD

**Issue by dmarkey** [ronaldoussoren/pyobjc#433]
Hey there,

Sorry, I'm a beginner using this library and the `Virtualization.Framework` seems to be missing Python binding documentation, so I'm trying to explore using the Apple documentation as a guide.. hitting some early snags, some methods seem to be missing:

```
In [20]: vmc = Virtualization.VZVirtualMachineConfiguration.alloc().init()

In [21]: vmc.validate()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-384d2940697d> in <module>
----> 1 vmc.validate()

AttributeError: 'VZVirtualMachineConfiguration' object has no attribute 'validate'
```
https://developer.apple.com/documentation/virtualization/vzvirtualmachineconfiguration/3656728-validate

I'm probably doing something stupid, and literally nobody seemed to have used to library yet (no references on Github)

Thanks for the guidance if you have time!

David

**Comment by dmarkey** [comment]
Sorry, I was using the swift API as a reference instead of the Objc one. Closing.

**Comment by ronaldoussoren** [comment]
FYI: Apple just posted an example for using this framework: <https://developer.apple.com/documentation/virtualization/running_macos_in_a_virtual_machine_on_apple_silicon_macs?language=objc>. There's example code for both Objective-C and Swift.
