### ISSUE TITLE
jaraco' package is required

### ISSUE THREAD

**Issue by MAKOMO** [ronaldoussoren/pyobjc#453]
Something seems to be wrong with the 8.4 pip package. I get

```
  File "Cocoa/__init__.pyc", line 9, in <module>
  File "AppKit/__init__.pyc", line 10, in <module>
  File "Foundation/__init__.pyc", line 9, in <module>
  File "CoreFoundation/__init__.pyc", line 9, in <module>
  File "objc/__init__.pyc", line 29, in <module>
  File "objc/_bridgesupport.pyc", line 15, in <module>
  File "pkg_resources/__init__.pyc", line 74, in <module>
  File "pkg_resources/extern/__init__.pyc", line 52, in create_module
  File "pkg_resources/extern/__init__.pyc", line 44, in load_module
ImportError: The 'jaraco' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

Downgraded to 8.2 and everything is fine again.

**Comment by ronaldoussoren** [comment]
Is this using py2app?

**Comment by MAKOMO** [comment]
Yes

**Comment by MAKOMO** [comment]
Maybe not related to 8.4 as I am no getting the same on 8.2. I am investigating what changed. Very strange.

**Comment by ronaldoussoren** [comment]
I expect that this is related to https://github.com/ronaldoussoren/py2app/issues/401, which should be fixed in py2app 0.27. If the bug isn't fixed in that version I have some more debugging to do.

**Comment by ronaldoussoren** [comment]
Setuptools, and pkg_resources in particular, has some special code for vendoring a number of packages. That code has confused py2app's dependency generator in the past and may have done so again.

**Comment by MAKOMO** [comment]
Thanks for the hint. I upgraded setuptools from 60.6.0 to 60.9.3. That might have been the cause. However, I am using an outdated py2app with some custom patches to get it running with PyQt6. I will try upgrading py2app to the pip version and see if that works for me. I will report.

**Comment by MAKOMO** [comment]
I think I shared those already and they should be in the 0.27 version if I remember correctly. I will check and if not of course send a PR. Thanks for both tools!

**Comment by MAKOMO** [comment]
I am closing this as pyobjc 8.4 was not the cause of the troubles.  py2app with current setuptools==60.9.3 seems to be the culprit.
