### ISSUE TITLE
Unicode problem with C pointer arguments

### ISSUE THREAD

**Issue by benwiggy** [ronaldoussoren/pyobjc#463]
There seems to be an error when passing strings that contain chars beyond U+0255 to ObjC methods that use C pointers in their arguments.

E.g. 
```
filename = '/path/to/file/with/Üƒ∂ßchars'
provider = CGDataProviderCreateWithFilename(filename.encode('utf8'))
```

gives: `ValueError: depythonifying 'char', got 'int' of wrong magnitude`

I've also tried encoding with 'raw_unicode_escape', which returns None if 'non-ASCII' characters are included.

Both of these encodings work, and a PDF Object (in this case) is returned if only ASCII characters are in the string.

Other methods are also affected, such as CFURLCreateFromFileSystemRepresentation.

**Comment by benwiggy** [comment]
Thank you so much! Really fast work! It's greatly appreciated.

**Comment by ronaldoussoren** [comment]
I've committed a change that fixes this, including a test addition that found the issues and ensures I don't reintroduce them later on.

My current plan is to release PyObjC 8.5 over the weekend, assuming nothing else comes up in pre-release testing.

**Comment by ronaldoussoren** [comment]
Reopening because I want to check for some other variants that might be problematic.

**Comment by ronaldoussoren** [comment]
The previous commit should fix all issues that I've been able to find, with a generic test that will warn when similar issues crop up in the future.
