### ISSUE TITLE
wheels not uploaded for many frameworks in 8.5 release

### ISSUE THREAD

**Issue by glyph** [ronaldoussoren/pyobjc#468]
I noticed for example that https://pypi.org/project/pyobjc-framework-UserNotificationsUI/#files lists only an sdist, no wheels.

**Comment by ronaldoussoren** [comment]
Sigh...

For some reason a number of wheels didn't get build with the last release and the build script didn't notice. I'm investigating and will upload the missing wheels later today.

**Comment by ronaldoussoren** [comment]
So much for obviously correct changes to scripts, a change in the wheel building script to enable parallel builds broke building wheels for packages that don't contain a C extension. 

I'm building the missing wheels using a patched script and will look into a proper fix later.  Luckily this bug does not affect the released distributions, just the scripts I use to build the release artefacts.

Thanks for the report!
