### ISSUE TITLE
Question: How to know the version of pyobjc from the Python code

### ISSUE THREAD

**Issue by macdeport** [ronaldoussoren/pyobjc#469]
All is in the title...

Because
```
import objc
print(objc.__version__)
```
⬇︎
```
None
```
and I am unable to find "version" in on-line documentation.

**Comment by ronaldoussoren** [comment]
``objc.__version__`` should give the right version:

```python
>>> import objc
>>> objc.__version__
'8.5b1'
```

What version of PyObjC is installed?  ``python -m pip list | grep pyobjc-core``

**Comment by macdeport** [comment]
Sorry, my question was because a ill conformed installation. Thanks for PyObjC and your answer.

**Comment by ronaldoussoren** [comment]
My pleasure.
