### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by yummyelin** [ronaldoussoren/pyobjc#473]
**Describe the bug**
Hi, I'm experiencing an error while installing one of pyobjc framework: pyobjc-framework-QTKit==6.2.2

**Platform information**
* Python version: 3.8
* How was python installed: homebrew
* macOS version: Mac Monterey 12.1
* other:
Package       |  Version
pip               |    22.1
setuptools | 62.2.0

**To Reproduce**
Steps to reproduce the behavior.
1. have this line `pyobjc-framework-QTKit==6.2.2; sys_platform == 'darwin'` in requirements.txt
2. run `pip install -r requirements.txt`

**Additional context**
```
...
Collecting pyobjc-framework-QTKit==6.2.2
  Using cached pyobjc-framework-QTKit-6.2.2.tar.gz (109 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_2/3r0w9ffj3k1fvj_91wpmhqs40000gq/T/pip-install-jfsgg0pr/pyobjc-framework-qtkit_f0b7383f9f7c4d2cbd0fc0b0709aaadf/setup.py", line 26, in <module>
          Extension(
        File "/private/var/folders/_2/3r0w9ffj3k1fvj_91wpmhqs40000gq/T/pip-install-jfsgg0pr/pyobjc-framework-qtkit_f0b7383f9f7c4d2cbd0fc0b0709aaadf/pyobjc_setup.py", line 436, in Extension
          % (tuple(map(int, os.path.basename(data)[6:-4].split("."))))
      ValueError: invalid literal for int() with base 10: ''
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I found a similar issue before https://github.com/ronaldoussoren/pyobjc/issues/343, python 3.8 is required for our project, will upgrading pyobjc-framework-QTKit to 7 work for me?

**Comment by yummyelin** [comment]
I finally downgrade pyobjc-framework-QTKit to 4.2.2 to make it work.

**Comment by S-Unit713** [comment]
Hello, 

I'm still getting the same  error while installing pyobjc-framework-QTKit==6.2.2

**Platform information**

Python version: 3.9.9
How was python installed: homebrew
macOS version: Mac Monterey 12.2.1
other:
Package | Version
pip        22.1.2
setuptools 63.1.0

Also, Downgrading pyobjc-framework-QTKit to 4.2.2 didnt work for me. Instead it gave me different error. 

is there any other other suggestion that I should Try?
