### ISSUE TITLE
Crash when creating an `NSAttributedString`

### ISSUE THREAD

**Issue by maxbelanger** [ronaldoussoren/pyobjc#476]
**Describe the bug**
PyObjC can crash when creating an `NSAttributedString`. 

**Platform information**
13.0 Beta (22A5286j)
arm64
`objc.__version__`: 8.5b1
Python: `Python 3.9.13 (main, May 24 2022, 21:13:51)`
Python installed via Homebrew, pyobjc via pip.

**To Reproduce**

1. Open an interactive Python shell.
2. Paste the following code:
```
from Cocoa import NSString, NSUTF16StringEncoding, NSMutableAttributedString, NSTextEncodingNameDocumentOption
htmlString = "hello: <a>ohai</a>"
htmlData = NSString.stringWithString_(htmlString).dataUsingEncoding_(NSUTF16StringEncoding)
attr_string, document_attributes = NSMutableAttributedString.alloc().initWithHTML_options_documentAttributes_(
        htmlData, dict(NSTextEncodingNameDocumentOption="UTF-16"), None)
```

**Expected behavior**
`attr_string` and `document_attributes` should be properly created.
Instead, the application crashes with `zsh: segmentation fault  python3`.

**Comment by ronaldoussoren** [comment]
The code works for me on macOS 12 (python.org installer for 3.10.5), I haven't tried to reproduce this on a 13 VM yet.

**Comment by ronaldoussoren** [comment]
I don't get this crash with the in-deveopment version of PyObjC (9.1) and Python 3.11 on an M1 system running macOS 13.1.  Python was installed using the installer on www.python.org.
