### ISSUE TITLE
CFPropertyListCreateData how to use？

### ISSUE THREAD

**Issue by SuperYogurt** [ronaldoussoren/pyobjc#491]
CFPropertyListCreateData(CFAllicatirGetDefault() data, kCFPropertyListBinaryFormat_v1_0, ???, ???)
I can't find the type of the fourth parameter and the fifth parameter now, how should I create it

**Comment by ronaldoussoren** [comment]
The function is documented here: https://developer.apple.com/documentation/corefoundation/1429998-cfpropertylistcreatedata?language=objc

```python
result, error = CFPropertyListCreateData(None, data, kCFPropertyListBinaryFormat_v1_0, 0, None)
if result is None:
   print("Error", error) # error will be an instance of CFError
else:
   print(result) # result will be an NSData object containing the serialised propertyless
```

The ``options`` argument must be 0 according to the documentation. The last argument is the error pointer. In general it is best to pass ``None`` here, you could also pass ``objc.NULL`` if you're not interested in a possible error value.  

Note that you could also use ``plistlib`` from the standard library if ``data`` contains basic Python types. That library has a more Pythonic interface than these low-level CoreFoundation APIs and also supports binary plists.
