### ISSUE TITLE
AttributeError: module 'objc' has no attribute 'initFrameworkWrapper'

### ISSUE THREAD

**Issue by jeanmatthieu** [ronaldoussoren/pyobjc#508]
It looks like `_bridgesupport.py` is gone after I pip installed pyobjc 9.0 which lead to various failures such as

```
AttributeError: module 'objc' has no attribute 'initFrameworkWrapper'
```

**Comment by jeanmatthieu** [comment]
Rolled back to  8.5.1 and that fixed the `AttributeError` issue

**Comment by ronaldoussoren** [comment]
I removed support for bridgesupport XML files in PyObjC 9, as mentioned in the changelog and warned about in the documentation.  PyObjC itself hasn't used these XML files in a long time and the system bridgesupport files have been broken even longer.

What is your use case for using this API?

**Comment by jeanmatthieu** [comment]
Hi Ronald, thanks for getting back to me. 
Apologies for missing the note in the changelog, I'll make the required changes in my code.

**Comment by ronaldoussoren** [comment]
I'm still interested in knowing why you were using this API (and likely bridgesupport files) and what I can do to make that use-case easier.

**Comment by jeanmatthieu** [comment]
I was loading a framework using `objc.initFrameworkWrapper`

```
import objc as
FMWK_PATH="/System/Library/PrivateFrameworks/OSPersonalization.framework"
__bundle__ = objc.initFrameworkWrapper("OSPersonalization",
                                        frameworkIdentifier="com.apple.OSPersonalization",
                                        frameworkPath=_objc.pathForFramework(FMWK_PATH),
                                        globals=globals())
```

I'm now using `objc.loadBundle`. 
```
import objc
__bundle__ = objc.loadBundle("OSPersonalization", vars(), 
                             "/System/Library/PrivateFrameworks/OSPersonalization.framework")
```

I've used `loadBundle` before and in other places but that code was just old and hadnt been updated yet.

**Comment by schriftgestalt** [comment]
I rely on the function, too. And I need the bridgesupport file to be loaded. 

The documentation is stating on several place that there are other ways to do that but there are no details about how to actually do it (only TODOs to). 

So removing a vital function without providing a working replacement is a bit annoying. Only because pyobjc is not using something doesn’t mean that it not used by someone else.

**Comment by ronaldoussoren** [comment]
@schriftgestalt, I've reverted the removal for (at least) the 9.x release and will keep it around until the replacement is ready for general use.   My plan was to have this done before the 9.0 release, but sadly I never got around to this and the tooling I'm using for PyObjC is not useable for anything but system frameworks.

I'm not sure yet when I'll push out 9.0.1, probably sometime during the coming week.

**Comment by schriftgestalt** [comment]
Thanks
