### ISSUE TITLE
How can I use instance methods off of my IBOutlet buttons, sliders, etc.

### ISSUE THREAD

**Issue by leifadev** [ronaldoussoren/pyobjc#509]
**Describe the bug**
Having trouble figuring out how to use instance methods on my IBOutlets.

For example, I have a NSLevelIndicator slider in a window in my XIB. I can get an instance of it in memory like this and use instance properties:
```py
@objc.IBAction
def changeDefinition_(self, sender):
    self.definitionField.setStringValue_("Squirrel: A fuzzy small animal that eats acorns")
    self.definitionField.setEditable_(False)
    print("Set string, and the text field is now locked...")
```
```
<NSLevelIndicator: 0x20be8ce20> # print(self.complexity)
```
However, I want to use an instance method on it like `tickMarkValueAtIndex:`, which will return its current value it's at as a double integer. I have tried following code:
```py
x = self.complexity.tickMarkValueAtIndex_()
print(x)
# or
x = self.complexity.alloc().init().tickMarkValueAtIndex_()
print(x)
```
Also, this one returns a value, what about methods that do a change or action to it too.

**Platform information**

* Python version: 3.9.2
* How was python installed: Homebrew
* macOS version: 10.15 Catalina

**To Reproduce**
Above what I said

**Expected behavior**
A print statement with the line `x = self.complexity.tickMarkValueAtIndex_()`
will return a number such as 33 out of 100 ticks.

**Additional context**
I can use properties though.

**Comment by ronaldoussoren** [comment]
``x = self.complexity.tickMarkValueAtIndex_(0)`` should work, that is you need to provide an argument to the method.

In general, calling methods of Objective-C objects works the same as for normal python objects (other than the weird naming of methods).
