### ISSUE TITLE
objc.error: NSInternalInconsistencyException - readFromData:ofType:error: is a subclass responsibility but has not been overridden

### ISSUE THREAD

**Issue by leifadev** [ronaldoussoren/pyobjc#513]
**Describe the bug**
I am running code to make an NSDocument object that reads a document using the `initWithContentsOfURL_ofType_error_`, however I get an error from Objective-C stating another method it's calling that "has not been overridden" or something.

**Platform information**

* Python version: 3.9.2
* How was python installed: python.org, path: `/Users/user123/PycharmProjects/shoutout/venv/bin/python3`
* macOS version: 13.0.1

**To Reproduce**
Run this:
```py
@classmethod
def write(cls, file: str):
    path = NSURL.fileURLWithPath_(file)
    ext = file.split('.')[-1]
    doc = NSDocument.alloc().initWithContentsOfURL_ofType_error_(path, ext, None)

cfiles.write("/Users/leif/Desktop/files.txt")
```
I get this, it doesn't work. it's using the `readFromData:ofType:error` method to read it first apparently, but that subclass isn't over ridden, I am not sure what that means. Anyways:
```
/Users/user123/PycharmProjects/shoutout/src/sutils/cfiles.py:27: UninitializedDeallocWarning: leaking an uninitialized object of type NSDocument
  doc = NSDocument.alloc().initWithContentsOfURL_ofType_error_(path, ext, None)
Traceback (most recent call last):
  File "/Users/user123/PycharmProjects/shoutout/src/sutils/cfiles.py", line 33, in <module>
    cfiles.write("/Users/leif/Desktop/files.txt")
  File "/Users/user123PycharmProjects/shoutout/src/sutils/cfiles.py", line 27, in write
    doc = NSDocument.alloc().initWithContentsOfURL_ofType_error_(path, ext, None)
objc.error: NSInternalInconsistencyException - readFromData:ofType:error: is a subclass responsibility but has not been overridden.
```

**Expected behavior**
No [NSInternalInconsistencyException][1], and it should return me the contents of whatever file string I used.

**Additional context**
I have looked everywhere for this error to be solved but I have had no luck. I have posted on stackoverflow and reddit [here](https://stackoverflow.com/questions/74568713/objc-error-nsinternalinconsistencyexception-readfromdataoftypeerror-is-a-s) but have had no responses yet.

Hopefully Ronald knows something about this, I checked all the examples and I couldn't find an instance of you using `initWithContentsOfURL_ofType_error_`, and only one instance of you using NSDocument at all which was ina function being called by Objective-C.

Any idea of what to do? I am lost here this is place is my only hope of solving this haha, thanks!

  [1]: https://developer.apple.com/documentation/foundation/nsinternalinconsistencyexception

**Comment by ronaldoussoren** [comment]
NSDocument is basically an abstract class. To use it you have to create a subclass of NSDocument that implements a number of required messages, which should be explained in the documentation for NSDocument.
