### ISSUE TITLE
CalendarStore reading stale data

### ISSUE THREAD

**Issue by mikaeleiman** [ronaldoussoren/pyobjc#525]
I have a Python web app that reads events from the user's calendar.

It seems that something, somewhere is using a cache that's not updated correctly when events change on the calendar side (don't know if it's on the Python side or the CalendarStore side).

What I do:

* Read events from a range of days
* Display it on the web page
* Update something in Calendar
* Re-import the events, stale data is read

It's specifically the duration of the event that gets the previous value; I calculate it thus:

```python
date = NSDateFormatter.localizedStringFromDate_dateStyle_timeStyle_(e.startDate(), Foundation.NSDateFormatterShortStyle, Foundation.NSDateFormatterShortStyle)
date = date.replace(",", "") # Haxx due to bug in macOS Mojave that added extra comma
    
start = datetime.datetime.strptime(date, "%Y-%m-%d %H:%M")
duration = e.endDate().timeIntervalSinceDate_(e.startDate())/60
```

It seems like that code could be simpler, but for some reason I did it like that (this was years ago). It's been working correctly, at least, until Ventura.

The code that reads the events looks like this:

```python
nsdate_start = NSDate.dateWithString_(start.strftime("%Y-%m-%d %H:%M:00 +00:00"))
nsdate_end = NSDate.dateWithString_(end.strftime("%Y-%m-%d %H:%M:00 +00:00"))
  
# get data from iCal
store = CalCalendarStore.defaultCalendarStore()
calendars = CalCalendarStore.calendars(store)
predicate = CalCalendarStore.eventPredicateWithStartDate_endDate_calendars_(nsdate_start, nsdate_end, calendars)

events = store.eventsWithPredicate_(predicate)
```

Restarting the Python script and re-importing gets the correct values, so it seems like it's specifically when re-reading events that have changed on the Calendar side since the first read something goes wrong.

**Platform information**

* PyObjC 9.0.1, also tested with 8.5.1
* Python version 3.10.9 from Homebrew
* macOS version 13.1

**Comment by ronaldoussoren** [comment]
I expect that this is a problem with the OS and not PyObjC. 

Note that the CalendarStore framework has been deprecated by Apple in macOS 10.8, the replacement is EventKit.

**Comment by mikaeleiman** [comment]
Ok, thanks! I'll have a look at moving to EventKit.
