### ISSUE TITLE
confusing error message when trying to save an event

### ISSUE THREAD

**Issue by georgpfolz** [ronaldoussoren/pyobjc#534]
When trying to save a new (calendar) event like this:

```
ek_store = EKEventStore.alloc().initWithAccessToEntityTypes_(0)
my_calendar = get_calendar(name='my calendar')   # custom function, works

my_event = EKEvent.alloc().init()
my_event.setEventStore_(ek_store)
my_event.setCalendar_(my_calendar)
my_event.setTitle_('test')
# some more code to set the start and end dates
print(f'{my_calendar.eventStore()=}')  # ek_store
print(f'{my_event.calendar().eventStore()=}')  # ek_store
print(f'{my_event.eventStore()=}')  # ek_store

done, err = ek_store.saveEvent_span_commit_error_(my_event, 0, 1, None)
```

strangely enough, I get the error message `Error Domain=EKErrorDomain Code=11 "That event does not belong to that event store." UserInfo={NSLocalizedDescription=That event does not belong to that event store.}`

That doesn't make sense to me, as the event and the calendar both seem to belong to the right event store. Is the error message misleading, or did I miss something? In that case, what would be the correct way to save the event?

**Comment by ronaldoussoren** [comment]
To fix this replace:

```python3

my_event = EKEvent.alloc().init()
my_event.setEventStore_(ek_store)
```

By:

```python3

my_event = EKEvent.evenWithEventStore_(ek_store)
```

``setEventStore_`` is not a documented API for ``EKEvent``.
