### ISSUE TITLE
framework-Security error

### ISSUE THREAD

**Issue by Alexandro1112** [ronaldoussoren/pyobjc#536]
** Can not return password from keychains via framework-Security. **
Hello, @ronaldoussoren. I trying get saved password from key-chains util via python.I had this script:
```
import Security

e = Security.SecKeychainFindGenericPassword(1, 10,
                                            'https://appstorrent.ru'.encode(), 
                                            len('https://appstorrent.ru'),
                                            'https://appstorrent.ru'.encode(),
                                            None,
                                            None,
                                            True)
print(e)
``` 
**Mac OS Big Sur 11.7.4** 
 * 3,9 * анаконда * 11.7.4 
 **Ожидаемое поведение** 
 The program should print the saved password from the keychain.

**However, program return: 
> (-50, 0, None, True)

How to solve the problem?

**Comment by ronaldoussoren** [comment]
-50 is the value for ``errSecParam``, which means "One or more parameters passed to the function are not valid." according to the Security framework documentation.

You get this error because you are passing the wrong arguments to this function, the Objective-C prototype for this function is:

```C

OSStatus SecKeychainFindGenericPassword(
       CFTypeRef keychainOrArray, 
       UInt32 serviceNameLength, 
       const char *serviceName, 
       UInt32 accountNameLength, 
       const char *accountName, 
       UInt32 *passwordLength, 
       void * _Nullable *passwordData, 
       SecKeychainItemRef  _Nullable *itemRef);
```

**Comment by Alexandro1112** [comment]
Thanks.As i knew, I need use ``ctypes`` for decode path to keychain framework to int32.
