### ISSUE TITLE
NSWindowCollectionBehaviorCanJoinAllApplications not present in AppKit

### ISSUE THREAD

**Issue by glyph** [ronaldoussoren/pyobjc#540]
I assume that this will be picked up when 13.0+ SDKs are added?

https://developer.apple.com/documentation/appkit/nswindowcollectionbehavior/nswindowcollectionbehaviorcanjoinallapplications?language=objc#

**Comment by ronaldoussoren** [comment]
Which version of PyObjC do you use? The constant should be present in PyObjC 9.0 or later (I've tested with 9.0.1 which is the current release).

```python3

from Cocoa import NSWindowCollectionBehaviorCanJoinAllApplications
```

**Comment by glyph** [comment]
Hmm. Sorry for the noise. I cannot reproduce this even in the environment where I had the issue originally. I must have been using an old version.
