### ISSUE TITLE
Add tests for passing ``NULL`` to sized array argument

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#541]
Need a test for an argument that has "c_array_length_in_arg" annotation and an ``objc.NULL`` or ``None`` value (both should result in passing ``NULL`` as this argument to the C function or method.

I ran into some code that indicates this currently doesn't work as expected.

**Comment by Alexandro1112** [comment]
Hello. @ronaldoussoren. I used PyObjC. After i saw error.It was written that the wrong type of variable was specified. Need ``charptr`` What is the type in python?

**Comment by ronaldoussoren** [comment]
> Hello. @ronaldoussoren. I used PyObjC. After i saw error.It was written that the wrong type of variable was specified. Need `charptr` What is the type in python?

Please don't comment on random issues to ask questions, that makes it likely that your question will get ignored.

In this case: The Python type for a charptr is ``bytes``.

**Comment by ronaldoussoren** [comment]
> Need a test for an argument that has "c_array_length_in_arg" annotation and an `objc.NULL` or `None` value (both should result in passing `NULL` as this argument to the C function or method.
> 
> I ran into some code that indicates this currently doesn't work as expected.

The additional test is not necesarry, problem was in the manual bindings for some Security functions (fixed in 0bfaf3ba9d4104b1784d9c502048305414ad560f)
