### ISSUE TITLE
What is wrong in this script?

### ISSUE THREAD

**Issue by Alexandro1112** [ronaldoussoren/pyobjc#543]
**Describe the bug**
I wrote script for detecting path to image on the background.
Bellow, script:

```
import AppKit,  Quartz
Id = Quartz.CGMainDisplayID()
boolean = AppKit.NSWorkspace.sharedWorkspace().desktopImageURLForScreen_(Id)
print(boolean)
```

I got error when run code:
In Apple Documentation said that need specify Screen ID. <br> Documentation: 
> https://developer.apple.com/documentation/appkit/nsworkspace/1530635-desktopimageurlforscreen

```
2023-03-26 18:03:25.839 Python[36521:1164026] -[OC_BuiltinPythonNumber deviceDescription]: unrecognized selector sent to instance 0x7ffc6ee4b350
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/pythonProject3/main.py", line 3, in <module>
    boolean = AppKit.NSWorkspace.sharedWorkspace().desktopImageURLForScreen_(Id)
ValueError: NSInvalidArgumentException - -[OC_BuiltinPythonNumber deviceDescription]: unrecognized selector sent to instance 0x7ffc6ee4b350
```

**Mac-os Big Sur**

* 3.10
* How was python installed python.org
* Mac version: 11.7.4

**Expected behaviour**
Script must return path to image, which set on screen.

**Comment by ronaldoussoren** [comment]
The argument for [``desktopImageForScreen:``](https://developer.apple.com/documentation/appkit/nsworkspace/1530635-desktopimageurlforscreen?language=objc) is an [``NSScreen*``](https://developer.apple.com/documentation/appkit/nsscreen?language=objc_) object, not a CoreGraphics display-id. 

I'm not aware of an API that will convert a CoreGraphics screen ID to an ``NSScreen*``, but it should be easy enough to find the right screen object for common setups (e.g. systems with 1 display or laptops with an external display).

**Comment by Alexandro1112** [comment]
Тhanks, I already understood what specify in argument.

>Id = Quartz.NSScreen.mainScreen()

 I pointed out this, and output was:
> file:///System/Library/Desktop%20Pictures/The%20Beach.heic
