### ISSUE TITLE
objc error when I created bridge between IOBluetooth

### ISSUE THREAD

**Issue by Alexandro1112** [ronaldoussoren/pyobjc#544]
**Display error**
```
 ValueError: NSInvalidArgumentException - *** +[IOBluetoothDevice<0x7fff817853c0> init]: cannot init a class object.
```
Bellow, code:
```
import objc


objc.loadBundle('IOBluetooth',    globals(), bundle_path=u'/System/Library/Frameworks/IOBluetooth.framework')


class IOBluetoothDevice_(IOBluetoothDevice):
     def init(self):
          self = super(IOBluetoothDevice_, self).init()
          self._inquiry = IOBluetoothDevice.batteryLevel_(self)
          return self
print(IOBluetoothDevice.init())
```
**Platform information**

* 3.10python
* python.org
* 11.7.4

**To Reproduce**
I created class with inheritance from ``IOBluetoothDevice``
**Expected behavior**
Script must return battery percent of paired device.

<p> What is wrong? <p>

**Comment by ronaldoussoren** [comment]
This is a duplicate for #545. As mentioned there: ``import IOBluetooth`` to access the IOBluetooth framework, and you are trying to use a private API that takes an ObjC block reference (which requires a metadata annotation to be used, but as this is a private API PyObjC doesn't ship with that metadata).
