### ISSUE TITLE
DEPRECATION: pyobjc-core is being installed using the legacy 'setup.py install' method

### ISSUE THREAD

**Issue by glyph** [ronaldoussoren/pyobjc#550]
**Describe the bug**

`pip install pyobjc` out of the box results in this error:

> DEPRECATION: pyobjc-core is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

**Platform information**

* Python version: 3.7-3.12
* How was python installed (python.org, anaconda, homebrew, ...): python.org, homebrew, and pyenv all behave similarly
* macOS version: 13.3.1/22E261

**To Reproduce**
`pip install` will do it in a fresh environment, although you may need 

**Expected behavior**
To install using pyproject.toml I guess?

**Additional context**
I think installing the `wheel` package might also work around this issue, but it seems clear that `pip` is steering folks towards

**Comment by ronaldoussoren** [comment]
To reproduce the issue: make sure a pip version before 23.1 is installed, with 23.1.1 installed the deprecation message goes away and pip uses the pyproject.toml build method (even with no such file in the archive).  The installation appears to be successful. 

If I read the linked pip issue correct that's expected: as of 23.1 pip will assume the use of ``--use-pep517`` when no pyproject.toml is present.

**Comment by ronaldoussoren** [comment]
https://github.com/ronaldoussoren/pyobjc/commit/b37f3808b0a23a4332336f2a3c5fbe2c4cffa0b8 adds a trivial pyproject.toml to all subproject to avoid the warning.

This is fairly annoying busy work, but I guess that's the price of progress.

**Comment by Alexandro1112** [comment]
That is mean for installation pyobjc 9.1.1, and  pip version 23.1?

**Comment by ronaldoussoren** [comment]
> That is mean for installation pyobjc 9.1.1, and pip version 23.1?

``pip install pyobjc`` should install pyobjc 9.1.1 without errors by way of using the binary wheels on PyPI.  Please let me know if that doesn't happen for you, and report the python version and the output of ``python3-m sysconfig | grep Platform``.

With recentish versions of pip before 23.1 you'll get a deprecation warning as mentioned the initial message for this issue, you can work around this by ensuring that ``wheel`` is installed (``pip install wheel`` before ``pip install pyobjc``).

The changeset I pushed earlier tonight explicitly opts pyobjc into the new method for building wheels to avoid problems later if the pip maintainers ever decide to drop the legacy build method.

**Comment by Alexandro1112** [comment]
I used command ``pip3 install PyObjC==9.1.1``. Installation has been successfully.

**Comment by ronaldoussoren** [comment]
Reopening because the minimal pyproject.toml somehow doesn't work for the framework bindings. The error says the 'pyobjc_setup' cannot be found, even though it is present in the checkout and sdist archives.
