### ISSUE TITLE
DisplayServices exit with 139 code.

### ISSUE THREAD

**Issue by Alexandro1112** [ronaldoussoren/pyobjc#562]
**Describe the bug**

I found a great ```DisplayServices``` framework and loaded it into python via pyobjc, with ```loadBundle``` I load 1 function,  for using in python. ```DisplayServicesGetBrightness``` to determine screen brightness, exited with code 139 after running python script.Look at this:

```

import objc


def load():

    objc._objc.loadBundleFunctions(objc.loadBundle('DisplayServices', bundle_path='/System/Library/PrivateFrameworks/DisplayServices.framework',  # noqa
                    module_globals=globals()), globals(), [('DisplayServicesGetBrightness', b'iI@')]) 
load()

CGDirectDisplayID = 1
print(globals()['DisplayServicesGetBrightness'](CGDirectDisplayID, None))
```

**MacOs Ventura 13.1 64 arch.**

* 3.11
* python.org
* 13.1

**To Reproduce**
Script should return value depending of screen brightness level.

**Expected behavior**
Return value depending of brightness level of screen.

**Additional context**
Earlier I use ```DisplayServicesGetBrightness``` for adjust brightness for determine display. Code successful adjust brightness.

**Comment by ronaldoussoren** [comment]
You're trying to call a private API, whether that works or not depends on the interface you somehow deduced. Crashes can occur when you get this wrong.  

According to https://github.com/nriley/brightness/blob/master/brightness.c the function has a different interface, in particular the second argument is a pointer to float where the value is returned (``o^f``) and the return value is a status code.
