### ISSUE TITLE
Code finished with 132 code.

### ISSUE THREAD

**Issue by Alexandro1112** [ronaldoussoren/pyobjc#567]
**Describe the bug**
I run my old script using PyObjc and Quartz.PDFKit for a working with pdf document in python.
Code return nothing.However code suddenly finished him working with ``Process finished with exit code 132 (interrupted by signal 4: SIGILL)``
And with minor warning ``2023-07-04 10:42:01.035 Python[78530:7591501] -[__NSCFString count]: unrecognized selector sent to instance 0x6000009a0630`` 
Bellow, I provide to you code.
```
import Quartz.PDFKit as pdf
import os
url  = pdf.NSURL.fileURLWithPath_(os.path.abspath(__file__) + 'sample.pdf')
PDFdocument = pdf.PDFDocument.alloc().initWithURL_(url)
print(PDFdocument.string())
index = PDFdocument.pageAtIndex_(1)
index.drawWithBox_toContext_(1, 'hello')
print(index.boundsForBox_(1).size)
index.writeToFile_('document.pdf')
```

**Platform information**

* 3.11
* Via python
* Ventura 13.3.1

**To Reproduce**
Although, code must exit with 0 exit code and return text in pdf document.

**Expected behavior**
Return string, and rewrite new document with new text in it.

**Comment by ronaldoussoren** [comment]
The code is buggy, in particular the ObjC definition for ``drawWithBox_toContext_`` is:

```objective-c

- (void)drawWithBox:(PDFDisplayBox)box 
          toContext:(CGContextRef)context;
```

The second argument of the method is a ``CGContextRef`` where your code passes a string.  Cocoa frameworks can crash hard when you pass objects of the wrong type (sadly). That's not something I can fix on my end.

Another issue is the last line: ``index.writeToFile_(...)``. The ``index`` variable refers to a PDFPage that doesn't have this method. You probably mean ``PDFdocument.writeToFile_(...)``.
