### ISSUE TITLE
NSURL should implement the os.PathLike protocol

### ISSUE THREAD

**Issue by mrpippy** [ronaldoussoren/pyobjc#577]
**Is your feature request related to a problem? Please describe.**
Passing NSURL objects (representing a file path) from ObjC to Python code can be tedious, I have a wrapper which calls `[NSURL fileSystemRepresentation]` and then copies that into an `NSString` to pass to Python code.

**Describe the solution you'd like**
If `NSURL` implemented the [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) protocol to make it a [path-like object](https://docs.python.org/3/glossary.html#term-path-like-object), Python file APIs would be able to use `NSURL` objects directly.

**Comment by ronaldoussoren** [comment]
Thanks. I like this idea.
