### ISSUE TITLE
Which version to use for macOS < 10.9 (primarily 10.5–10.6)?

### ISSUE THREAD

**Issue by barracuda156** [ronaldoussoren/pyobjc#587]
There is PR in Macports lowering supported macOS to 10.9: https://github.com/macports/macports-ports/pull/21935
It is perhaps unfeasible to support older OS in the current version of `pyobjc`, but from the history it seems that much older OS were supported at some point.

@ronaldoussoren Could you recommend which version is a better pick as a fallback for 10.5–10.6 (i.e., including powerpc systems with gcc as the compiler)?

**Comment by ronaldoussoren** [comment]
IIRC PyObjC 6.2.2 is the last version that supports 32-bit code, IIRC that's also the last version that contained code supporting PPC.

Note that these older versions of PyObjC may have problems when used with newer versions of Python.  PyObjC at some points interact with the CPython API at a fairly low level and also has knowledge about the byte code format for detecting the default C signature of methods. I primarily expect issues with later, there have been some changes to the byte code format over the years that have affected PyObjC.

**Comment by barracuda156** [comment]
@ronaldoussoren Thank you! I will try that one.

**Comment by barracuda156** [comment]
Indeeds, with Python 3.11 it fails:
```
--->  Building py311-pyobjc
sphinx-build-3.11 -b html -d _build/doctrees . _build/html
Running Sphinx v7.2.6
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://altgraph.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://macholib.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://modulegraph.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://py2app.readthedocs.io/en/latest/objects.inv...

Extension error (examples):
Handler <function build_examples at 0x3ea0758> for event 'builder-inited' threw an exception (exception: invalid mode: 'rU')
hello <sphinx.application.Sphinx object at 0x35009d0>
Fetching example Scripts/autoreadme from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_python_py-pyobjc/py311-pyobjc/work/pyobjc-6.2.2/pyobjc-core/Examples/Scripts/autoreadme.py
make: *** [html] Error 2
```
But the same version builds (with some warnings) with Python 3.9 for `ppc`.

**Comment by barracuda156** [comment]
P. S. @ronaldoussoren Thanks again. I will submit the fallback version to Macports, we just decided to rather do it in a separate port, therefore the first PR is closed.
