### ISSUE TITLE
proxy os.PathLike to a file-like NSURL

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#589]
os.PathLike is similar to Cocoa's use of NSURL to represent paths. Proxy os.PathLike to NSURL to allow using `pathlib.Path` values where framework's expect a file URL.

NSSecureCoding could be an issue here, NSURL implements this protocol whereas PyObjC cannot claim to support that protocol for arbitrary Python objects. It should be possible to do this for pathlib's classes though (I'm thinking of encoding those basically as the base NSURL, leaving the pickle-based implementation of NSCoding for other PathLike classes).

**Comment by RhetTbull** [comment]
This is wonderful! Looking forward to trying this in 10.2. Thanks for all your work on pybojc -- I use it every day in a number of projects.
