### ISSUE TITLE
Question: trying to grab a screenshot using ScreenCaptureKit

### ISSUE THREAD

**Issue by Saba-Sabato** [ronaldoussoren/pyobjc#590]
Hello,
This is the first time I've used PyObjC. I'm trying to grab a screenshot in Python, using `ScreenCaptureKit`, adapting the code from this [Apple Videos](https://developer.apple.com/videos/play/wwdc2023/10136/?time=746) guide. (go to `code` tab, bottom two code blocks)
I've encountered several problems along the way, and I'm here to ask if I've just gone about this completely the wrong way. I went through the [PyObjC documentation](https://pyobjc.readthedocs.io/en/latest/) and the relevant Apple documentation pages: [ScreenCaptureKit](https://developer.apple.com/documentation/screencapturekit), [captureImageWithFilter](https://developer.apple.com/documentation/screencapturekit/scscreenshotmanager/4251334-captureimagewithfilter?language=objc), [SCContentFilter](https://developer.apple.com/documentation/screencapturekit/sccontentfilter?language=objc), [SCShareableContent](https://developer.apple.com/documentation/screencapturekit/scshareablecontent?language=objc).
Here is the code I have so far:
```python
from time import sleep
import objc
from ScreenCaptureKit import (
    SCContentFilter,
    SCScreenshotManager,
    SCStreamConfiguration,
    SCShareableContent,
)
import Quartz.CoreGraphics as CG


def capture_screenshot():
    SCShareableContent.getShareableContentWithCompletionHandler_(
        shareable_content_callback
    )
    sleep(1)  # Without this, the handlers are never executed

def shareable_content_callback(shareable_content, error=None):
    display = shareable_content.displays()[0]
    content_filter = SCContentFilter.alloc().initWithDisplay_excludingWindows_(
        display, []
    )
    configuration = SCStreamConfiguration.alloc().init()

    SCScreenshotManager.captureImageWithFilter_configuration_completionHandler_(
        content_filter, configuration, cg_image_handler
    )

    content_filter.dealloc()
    configuration.dealloc()

def cg_image_handler(cg_image_ref, error=None):
    # Process my CGImage e.g. write it out to file
    pass

def main():
    with objc.autorelease_pool():
        capture_screenshot()

if __name__ == "__main__":
    main()
```

I can't figure out how to write normal, synchronous code to get the screenshot. The function `captureImageWithFilter` has a required parameter `SCContentFilter`, which is initialized with a [SCDisplay](https://developer.apple.com/documentation/screencapturekit/sccontentfilter/3919806-initwithdisplay?language=objc). To get that I need to call [getShareableContentWithCompletionHandler](https://developer.apple.com/documentation/screencapturekit/scshareablecontent/3916733-getshareablecontentwithcompletio?language=objc) which takes as a parameter a _completion handler_. That handler will receive the resulting `SCDisplay`. Only then can I create the parameters required to call `captureImageWithFilter` which in turn receives yet another handler, and only that final handler will have the `CGImage`. This feels like **callback hell**, and I'm sure it's not the way it's supposed to be called. What is the correct way to do this?

Thank you very very much,
Saba

**Comment by ronaldoussoren** [comment]
You need runloop to wait for the completion handler to be called. 

Also don't call `dealloc` methods, that will result in hard crashes. That's similar to why you don't need to call `__del__` in Python, although you won't get hard crashes when you do so.

**Comment by torablien** [comment]
@Saba-Sabato I am also learning pyobjc and trying to grab a screenshot with `ScreenCaptureKit`. Did you ever get this working / have a working code example you can share?

Thanks! :)

**Comment by torablien** [comment]
Hi @ronaldoussoren, not sure if this is the right place to ask such a question (feel free to redirect) but could you provide some more context (or a reference) on how to properly wait for the completion handler to be called? 

Like the original reporter, I'm trying to write a simple synchronous function that returns (or raises) after screen capture. 

I tried some simple implementations with `AppHelper.runConsoleEventLoop()` and `Foundation.CFRunLoopRun()` but couldn't get them to work well (e.g. terminating program, hanging if there is an error, etc). 


Basic example:

```(python)
def capture_screen(save_path: str):
    from ScreenCaptureKit import (
        SCContentFilter,  # type: ignore
        SCScreenshotManager,  # type: ignore
        SCStreamConfiguration,  # type: ignore
        SCShareableContent,  # type: ignore
    )
    from AppKit import NSBitmapImageFileTypePNG, NSBitmapImageRep  # type: ignore
    import Quartz
    import time

    def shareable_content_completion_handler(shareable_content, error):
        if error:
            raise Exception(f"Shareable content completion handler error: {error}")

        if not shareable_content:
            raise Exception("No shareable content in completion handler.")

        if not shareable_content.displays():
            raise Exception("No displays in shareable content in completion handler.")

        display = shareable_content.displays()[0]

        content_filter = SCContentFilter.alloc().initWithDisplay_excludingApplications_exceptingWindows_(
            display,
            [],
            [],
        )

        configuration = SCStreamConfiguration.alloc().init()
        SCScreenshotManager.captureImageWithFilter_configuration_completionHandler_(
            content_filter, configuration, capture_image_completion_handler
        )

    def capture_image_completion_handler(image, error):
        if error:
            raise Exception(f"Capture image completion handler error: {error}")

        if not image:
            raise Exception("No image in completion handler.")

        bitmap_rep = NSBitmapImageRep.alloc().initWithCGImage_(image)

        if not bitmap_rep:
            raise Exception("Failed to create bitmap image representation.")

        png_data = bitmap_rep.representationUsingType_properties_(
            NSBitmapImageFileTypePNG, None
        )
        if not png_data:
            raise Exception("Failed to convert image to PNG format.")

        png_data.writeToFile_atomically_(save_path, True)
        print(f"Screenshot saved as {save_path}.")

    SCShareableContent.getShareableContentWithCompletionHandler_(
        shareable_content_completion_handler
    )

    time.sleep(1)  # TODO: replace with more robust approach


def main():
    capture_screen(
        save_path="screenshot.png",
    )

    print("Screenshot captured.")

    with open("screenshot.png", "rb") as f:
        print(f"Screenshot size: {len(f.read())}")


main()
```

**Comment by Saba-Sabato** [comment]
@torablien Hey, no, unfortunately I couldn't get ScreenCaptureKit to work. I painstakingly collected information scattered throughout the whole damn web just to get this simple example to work, after which I dropped the subject. I eventually went with another approach, here is some sample code to get you started:
```python
from pathlib import Path

import Foundation
import Quartz
import UniformTypeIdentifiers
import objc


def write_screenshot_to_file(path: Path | str):
    screenshot = get_screenshot()
    url = convert_path_to_ns_url(path)
    result = write_image_to_file(screenshot, url)
    assert result is True, "Failed writing screenshot to file"
    return


def get_screenshot():
    return Quartz.CGDisplayCreateImage(Quartz.CGMainDisplayID())


def convert_path_to_ns_url(path: Path | str):
    if isinstance(path, str):
        path = Path(path)
    url = Foundation.NSURL.fileURLWithPath_(str(path.absolute()))
    return url


def write_image_to_file(image, path):
    dest = Quartz.CGImageDestinationCreateWithURL(
        path, UniformTypeIdentifiers.UTTypeJPEG.identifier(), 1, None
    )
    assert dest is not None, "Error creating destination, check parameters?"
    Quartz.CGImageDestinationAddImage(dest, image, None)
    result = Quartz.CGImageDestinationFinalize(dest)
    return result


def main(path: Path | str):
    with objc.autorelease_pool():
        write_screenshot_to_file(path)


if __name__ == "__main__":
    main(Path.cwd() / "screenshot.jpeg")
```
Good luck!
