### ISSUE TITLE
Question about API usage

### ISSUE THREAD

**Issue by schriftgestalt** [ronaldoussoren/pyobjc#597]
Sorry if that is the wrong place to ask this.

I have an macOS app written in ObjectiveC that embeds python and uses pyobjc to let users write scripts inside the app.

I like to add some root objects (NSObjets) to the global dict so that the scripts can access them. I found a way to use the python/pyobjc c-APIs to do this. 
first "load" pyobjc when initializing python.
```
PyObjC_API = (struct pyobjc_api*)PyCapsule_Import("objc." PYOBJC_API_NAME, 0);
```
later, just before the script is run:
```
PyObject *pyObj = PyObjC_API->id_to_python(rootObject); 
PyDict_SetItemString(global_dict, "rootObject", pyObj);
```

1) Is this save with different versions of pyobjc, meaning is the `PyObjC_API` struct stable?
2) Is there a simpler way to load the `id_to_python` function. As that is all I need? 
3) Is there a better way to do this altogether?

p.s.
The actual script is executed by `PyRun_SimpleFile()`.

**Comment by ronaldoussoren** [comment]
This is a good place to ask questions like this, but sadly I don't have a really good answer at this time.  My current plan is to work on a proper embedding API when I start work on adding support for free threading and sub interpreters. Especially for the latter as adding support for that would almost certainly require breaking changes to the APIs you're currently using.  I have no time frame as to when this will happen. I'll ping you when I have a proposal for an embedding API.

As to your questions:

1.  The struct is fairly stable, but you should check the `api_version` field first. 

     The version field will change when I remove fields from the struct, or change existing members. I do add new members from time to time without updating the version.
     
2. No, there is no other way to load this function

3. Not yet, see above.


To be pedantic: Both the `PyObjC_API` interface and classes like `OC_PythonObject` are internal APIs of PyObjC and as such subject to change. That said, these APIs have been fairly stable over the years and I have no plans to change them without good reasons.

**Comment by schriftgestalt** [comment]
Thank you.
