### ISSUE TITLE
what's a native-selector?

### ISSUE THREAD

**Issue by nullhook** [ronaldoussoren/pyobjc#598]
i'm trying to introspect methods using c++ but in objc runtime was curious what the following types are in objective-c? this is Metal.framework specific.

```
<native-selector libraryDataContents of <_MTLLibrary: 0x600002c7c640>
    label = <none> 
    device = <AGXG13XDevice: 0x11a840000>
        name = Apple M1 Max 
    ...>
```

what type is native-selector here?

**Comment by nullhook** [comment]
looks like it's a `objc.native_selector` type and defining class is _MTLLibrary but `isClassMethod` is false. if it's not a class method, what is it then?

**Comment by ronaldoussoren** [comment]
> i'm trying to introspect methods using c++ but in objc runtime was curious what the following types are in objective-c? this is Metal.framework specific.

PyObjC is a Python library, not C++ ;-)
> 
> ```
> <native-selector libraryDataContents of <_MTLLibrary: 0x600002c7c640>
>     label = <none> 
>     device = <AGXG13XDevice: 0x11a840000>
>         name = Apple M1 Max 
>     ...>
> ```
> 
> what type is native-selector here?

Native-selector is the Python representation of a method in Objective-C (whose names are commonly called selectors). E.g. this is a callable object that when invoked will call a method of the `_MTLLibrary` object.
