### ISSUE TITLE
AppKit: Can't get list of windows for a given NSApplication instance

### ISSUE THREAD

**Issue by trevorstr** [ronaldoussoren/pyobjc#599]
**Describe the bug**

I am trying to obtain a list of windows for an `NSApplication` instance.
However, the `windows()` variable seems to be missing from the `NSApplication` class in PyObjC.

```python
from AppKit import NSWorkspace

app_list = NSWorkspace.sharedWorkspace().runningApplications()

for app in app_list:
    if app.bundleIdentifier() == 'com.google.Chrome':
        print(app.windows())
```

```
AttributeError: 'NSRunningApplication' object has no attribute 'windows'
```

**Platform information**

* Python version 3.12
* How was python installed (python.org, anaconda, homebrew, ...) Homebrew & using venv
* macOS version Sonoma 14.4.1

**To Reproduce**

See script above

**Expected behavior**

According to the documentation for AppKit, there's supposed to be a `windows` variable exposed from the `NSApplication` class, which returns an array of windows for the application.

https://developer.apple.com/documentation/appkit/nsapplication/app_windows

**Comment by mrpippy** [comment]
`NSWorkspace.sharedWorkspace().runningApplications()` returns an array of [`NSRunningApplication`](https://developer.apple.com/documentation/appkit/nsrunningapplication?language=objc) objects, not [NSApplication]. If you want to get the list of open windows in another app, you'll likely need to use AppleScript/Apple Events.

**Comment by ronaldoussoren** [comment]
> `NSWorkspace.sharedWorkspace().runningApplications()` returns an array of [`NSRunningApplication`](https://developer.apple.com/documentation/appkit/nsrunningapplication?language=objc) objects, not `NSApplication`. If you want to get the list of open windows in another app, you'll likely need to use AppleScript/Apple Events.

Indeed. The ScriptingBridge framework is a fairly easy way to interact with AppleScript/AppleEvents, and you can use the `Script Editor` application to check what applications support.
