### ISSUE TITLE
Little memory leak of 16-byte OC_BuiltinPythonArray

### ISSUE THREAD

**Issue by mansourmoufid** [ronaldoussoren/pyobjc#603]
Hi,

I'm working with IOSurfaces again, applying filters and displaying them in a loop. I noticed a tiny memory leak, a few kilobytes per minute, just big enough to notice in Activity Monitor. I just upgraded to PyObjC version 10.2 after years on 8 point something.

Instruments' allocation profiler shows hundreds of persistent 16-byte OC_BuiltinPythonArray:

<img width="1284" alt="Capture d’écran, le 2024-04-17 à 21 11 13" src="https://github.com/ronaldoussoren/pyobjc/assets/10801249/810e4949-fe35-4559-a06b-f977ab49cf40">

The stack trace is:

```
_objc_rootAllocWithZone	
+[NSArray allocWithZone:]	
+[OC_PythonArray arrayWithPythonObject:]	
depythonify_python_object	
depythonify_c_value	
method_stub	
ffi_closure_SYSV_inner	
ffi_closure_SYSV	
ffi_call_SYSV	
ffi_call_int	
PyObjCFFI_Caller	
objcsel_call	
_PyObject_MakeTpCall	
call_function	
_PyEval_EvalFrameDefault	
function_code_fastcall	
method_vectorcall	
PyVectorcall_Call	
_PyEval_EvalFrameDefault	
function_code_fastcall	
call_function	
_PyEval_EvalFrameDefault	
function_code_fastcall	
call_function	
_PyEval_EvalFrameDefault	
function_code_fastcall	
method_vectorcall	
PyVectorcall_Call	
t_bootstrap	
pythread_wrapper	
_pthread_start	
thread_start	
```

There are about 72 allocations per second. I think the ffi_closure means it's happening in a ctypes callback. I have a bunch of callback functions on an NSTimer (not with PyObjC, some native UI library) but those are all either 10 or 100 times per second.

I don't know what `OC_BuiltinPythonArray` is.

I tried to find where I'm passing an array to PyObjcC but I can't pinpoint where. I don't think I'm doing that at all. I'll try to look at the PyObjC source and understand it, but I could really use some advice where to begin.

**Comment by ronaldoussoren** [comment]
OC_BuiltinPythonArray.m is used to proxy builtin sequence types (list and tuples) to Objective-C as subclasses of `NS(Mutable)Array`.  The actual code is in OC_PythonArray.m, the OC_BuiltinPythonArray class is a subclass that's used to support secure coding for builtin classes but contains not real code.

That said, the class itself is likely a red herring.  This may be related to how the API is used which might lead to an increased retain count for objects.  I'd expect test failures in the PyObjC test suite when these instances have the wrong refcount generically. 

If you can reproduce this in code that you can share publicly I can try to reproduce the issue on my end.

**Comment by mansourmoufid** [comment]
Thanks for the info, I'll come up with a small demo to reproduce the issue.

I think it'll take me a while to figure this out, so I'll close this for now and check back in later. I'll try to find out what's in the Python object, maybe with PyObject_Print...
