### ISSUE TITLE
Building 10.2 results in failure due to BrowserEngineKit

### ISSUE THREAD

**Issue by WardsParadox** [ronaldoussoren/pyobjc#605]
**Describe the bug**
When installing with pip to compile, pyobjc-framework-BrowserEngineKit always fails to build it's wheel with:
```sh
      Modules/_BrowserEngineKit.m:6:9: fatal error: 'BrowserEngineKit/BrowserEngineKit.h' file not found
      #import <BrowserEngineKit/BrowserEngineKit.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```

**Platform information**

* Python version - 3.10.14
* How was python installed (python.org, anaconda, homebrew, ...) - Python.org, homebrew, standalone-python,etc
* macOS version - macOS 14.4, macOS 14.5 beta 4

**To Reproduce**
`pip install --no-cache --no-binary :all: pyobjc`

**Expected behavior**
Wheel built as expected.

**Additional context**

**Comment by ronaldoussoren** [comment]
Do you have the most recent Xcode or Compiler Tools installed?  The PyObjC build process assumes that the most recent SDK for the current OS is available.

As a workaround, don't use `--no-binary :all:`.

**Comment by WardsParadox** [comment]
Dropping back to 10.1 worked. Will update Xcode to latest and try again.

**Comment by WardsParadox** [comment]
Yup that worked.
