### ISSUE TITLE
No way to define installation directory

### ISSUE THREAD

**Issue by nieder** [ronaldoussoren/pyobjc#612]
**Is your feature request related to a problem? Please describe.**
When running `pythonX.Y ./install.py`, the framework wrappers install to $PREFIX/lib/pythonX.Y/site-packages/$FRAMEWORK, and if that's write restricted, to $HOME/.local/lib/pythonX.Y/site-packages. Sometimes, the install might be preferred to go elsewhere.

**Describe the solution you'd like**
Ability to define a separate installation directory when calling `./install.py`.

**Describe alternatives you've considered**
MacPorts has a script that builds things and generates wheels, but it requires the macports infrastructure. I've tried editing _install_tool.py around `build_project()` to add `--root` or `--prefix`, but things are not quite working as I expected.

**Additional context**
This is in the context of building pyobjc purely from source, without having to download deps or wheels, and the ability to send the built wrappers to a target directory of choice (or have the created .whl saved in a readily available location).

**Comment by ronaldoussoren** [comment]
``development-support/collect-dist-archives`` will create wheels, but for all installed supported python versions. This is the script used for creating the release artefacts on PyPI.

What's your use case for building from source like this?

**Comment by ronaldoussoren** [comment]
A script that invokes ``_install_tool("--target", "/path/to/target")`` would likely work. That said, this is not a feature that I'll implement in the repository (and I won't merge a PR that would add a command-line option for this to the install scripts).
