### ISSUE TITLE
keyword arguments for __new__ method generated from initWith* are weird if all caps

### ISSUE THREAD

**Issue by rndblnch** [ronaldoussoren/pyobjc#623]
The automatic generation of keyword arguments name for __new__ method from initWith* just turns the first letter of the first argument to lowercase.
But when the first argument is all caps it seems not appropriate, eg:

pdf = PDFDocument.alloc().initWithURL(url)
leads to
pdf = PDFDocument(uRL=url)
(notice the weird uRL parameter)

I have a small patch for Lib/objc/_transform.py fixing that, will open a PR

**Platform information**

pyobjc 10.3+

**Comment by ronaldoussoren** [comment]
Thanks for the report and fix. I've slightly tweaked your patch to properly handle "initWithX:y:" and added a test case.
