### ISSUE TITLE
NSIndexSet.alloc().initWithIndex_ segfaults

### ISSUE THREAD

**Issue by Sbte** [ronaldoussoren/pyobjc#625]
**Describe the bug**

The following code segfaults:

```Python
from Foundation import NSIndexSet
s = NSIndexSet.alloc().initWithIndex_(0)
```

This is used in `array_property` so using `array_property` also causes segfaults.

Note that `NSIndexSet.indexSetWithIndex_(0)` works fine.

**Platform information**

* Python version
3.12.6
* How was python installed (python.org, anaconda, homebrew, ...)
homebrew
* macOS version
14.7, but also happens on 13.6.6

**Comment by rndblnch** [comment]
this looks very similar to the old #271

**Comment by rndblnch** [comment]
the fix for #271 is specific to NSData, it can be found in this commit: bf601d4

**Comment by ronaldoussoren** [comment]
Thanks. 

I'm currently travelling and will look into this when I'm back home.

**Comment by ronaldoussoren** [comment]
@rndblnch: #271 is relevant, I'm tweaking that workaround to be more general. Thanks for the tip, that made finding a workaround a lot easier.

**Comment by rndblnch** [comment]
> @rndblnch: #271 is relevant, I'm tweaking that workaround to be more general. Thanks for the tip, that made finding a workaround a lot easier.

glad it helped, it's pure chance that I saw this one while reporting something else, and it rang a bell.
after some digging I found the bug I reported 5 years ago …
thanks again for your work.

**Comment by Sbte** [comment]
That indeed seems to have fixed the issue, also when using `array_property`. Thanks a lot!
