### ISSUE TITLE
Quartz module fails to build on macOS 15: CGWindowListCreateImageFromArray is unavailable

### ISSUE THREAD

**Issue by breun** [ronaldoussoren/pyobjc#627]
**Describe the bug**

Why I try to build the PyObjC Quartz module on macOS 15, I get this error:

```
Modules/_coregraphics.m:243:17: error: 'CGWindowListCreateImageFromArray' is unavailable: obsoleted in macOS 15.0 - Please use ScreenCaptureKit instead.
  243 |                 CGWindowListCreateImageFromArray(screenBounds, windowArray, imageOption);
      |                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGWindow.h:280:33: note: 'CGWindowListCreateImageFromArray' has been explicitly marked unavailable here
  280 | CG_EXTERN CGImageRef __nullable CGWindowListCreateImageFromArray(
      |                                 ^
```

**Platform information**

* Python 3.12
* Installed from MacPorts (`python312`)
* macOS 15.0.1

**To Reproduce**
Build the PyObjC Quartz module on macOS 15.

**Expected behavior**
I expect the build to succeed without errors.

**Comment by breun** [comment]
I found a workaround for MacPorts by setting the deployment target to macOS 14: https://trac.macports.org/wiki/SequoiaProblems#ScreenCaptureKitRequirementwithmacOS15SDK

**Comment by ronaldoussoren** [comment]
Thanks for the report. I generally build with the Python.org installations of Python and hadn't seen this problem yet.
