### ISSUE TITLE
Question: Wish examples about blocks

### ISSUE THREAD

**Issue by izwb003** [ronaldoussoren/pyobjc#631]
Sorry that I'm completely a beginner, but it seems to be nowhere else to find the answer except here...

I'm trying to use PyObjC to communicate with a private bundle ```MediaRemote``` to get the info of the now playing media. In this bundle there is a function defined like this:

```c
typedef void (^MRMediaRemoteGetNowPlayingInfoCallback)(NSDictionary *info);
void MRMediaRemoteGetNowPlayingInfo(dispatch_queue_t queue, MRMediaRemoteGetNowPlayingInfoCallback block);
```

I can get other functions in this bundle properly with ```objc.loadBundle()``` and ```objc.loadBundleFunctions()```, But here it confused me - ```MRMediaRemoteGetNowPlayingInfoCallback``` is an Objective-C block.

I tried like this:

```py
bundle = objc.loadBundle("MediaRemote", globals(), "/System/Library/PrivateFrameworks/MediaRemote.framework")
objc.loadBundleFunctions(bundle, globals(), [
            ("MRMediaRemoteGetNowPlayingInfo", b"v@@?")
        ])
MRMediaRemoteGetNowPlayingInfo(dispatch.dispatch_get_global_queue(dispatch.DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ?)
```

I read the explaination in the [documentation](https://pyobjc.readthedocs.io/en/latest/core/blocks.html) but I still don't understand what is "an arbitrary callable" here for the second argument. I tried many things like python method, lambda, classes with ```__call__```, decorate with ```objc.signature()```,  etc. but none of them works. It keeps giving me an ```OC_PythonException```: ```'<class 'TypeError'>: Argument 1 is a block, but no signature available'```. I tried to search for any examples, but was surprised to find that there was almost no example explaining this situation.

So may I have any example about this situation? I'm not very familiar with the details of Objective-C metadata, but a simple explaination/example about this will be very helpful.

**Comment by ronaldoussoren** [comment]
The documentation is very sparse on using custom metadata, which is needed to use blocks. For all public frameworks the bindings for that framework include the required additional information.


This should do the trick:

```python
objc.loadBundleFunctions(
    bundle,
    globals(),
    [
        (
            "MRMediaRemoteGetNowPlayingInfo",
            b"v@@?",
            "",
            {
                "arguments": {
                    1: {
                        "callable": {
                            "arguments": {
                                0: {"type": b"^v"},
                                1: {"type": b"@"},
                            },
                            "retval": {"type": b"v"},
                        }
                    }
                }
            },
        )
    ],
)
```

This adds "callable" metadata for argument 1 (the block), with a single real argument of type ``id`` and a ``void`` return value. The 0-th argument is magic for blocks and should always have type "^v".

BTW. You may want to look into using a public API for this, see <https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter?language=objc>

**Comment by izwb003** [comment]
> The documentation is very sparse on using custom metadata, which is needed to use blocks. For all public frameworks the bindings for that framework include the required additional information.
> 
> 
> 
> 
> 
> This should do the trick:
> 
> 
> 
> ```python
> 
> objc.loadBundleFunctions(
> 
>     bundle,
> 
>     globals(),
> 
>     [
> 
>         (
> 
>             "MRMediaRemoteGetNowPlayingInfo",
> 
>             b"v@@?",
> 
>             "",
> 
>             {
> 
>                 "arguments": {
> 
>                     1: {
> 
>                         "callable": {
> 
>                             "arguments": {
> 
>                                 0: {"type": b"^v"},
> 
>                                 1: {"type": b"@"},
> 
>                             },
> 
>                             "retval": {"type": b"v"},
> 
>                         }
> 
>                     }
> 
>                 }
> 
>             },
> 
>         )
> 
>     ],
> 
> )
> 
> ```
> 
> 
> 
> This adds "callable" metadata for argument 1 (the block), with a single real argument of type ``id`` and a ``void`` return value. The 0-th argument is magic for blocks and should always have type "^v".
> 
> 
> 
> BTW. You may want to look into using a public API for this, see <https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter?language=objc> 
> 
> 
> 
> 

Ah I see it! So that means I must add the metadata dictionary to tell PyObjC more about this function on its arguments, clearly declare this ```callable```'s details. Just a signature ```b"@?"``` is not enough.

With this trick now I can use a python function as the 2nd argument. I used to thought a python function cannot work as an Objective-C block, but now it's clear that's because I didn't tell PyObjC enough information.

It takes some time to understand the document about the metadata as a beginner, but with examples and digging into sources to find how documented APIs' metadata was defined it seems not very complex. I will try to learn more.

Thank you for your professional view!

BTW, the ```MPNowPlayingInfo``` series API seems to be used for setting media info to the system, however I'd like to get these information, which I believe only ```MRMediaRemote``` can do...
